### ISSUE TITLE
Further Geoip Support

### ISSUE THREAD

**Issue by aimdev** [pmacct/pmacct#135]
Are there any plans to extend Geoip functions?
Currently I can get the country code out, however the ability to get the latitude/longitude
for further processing in elastic search, via Pierky's interface would be useful.

Thanks

Aimee

**Comment by paololucente** [comment]
Hi Aimee,

Please follow-up by unicast email. The feature is totally doable, we should only look into timing, i'd somehow need a dataset from you in order to make a meaningful development. 

As a side note, current code also supports pocode - does it help? Maxmind library documentation, says: "Latitude and Longitude are often near the center of population. These values are not precise and should not be used to identify a particular address or household.". Basing on this description, pocode should actually be same resolution if not better. 

Cheers,
Paolo
