### ISSUE TITLE
Results exported via Kafka are different from using print method

### ISSUE THREAD

**Issue by mpergament** [pmacct/pmacct#14]
Using "nfacctd  -c timestamp_start, in_iface, out_iface -P print -l 50020" I get correct (expected) results which is 6000 packets/sec. However If I use kafka results are 1000-2000 packets/sec (analysed json messages produced by nfacctd). Any ideas why I get wrong results using Kafka?

**Comment by mpergament** [comment]
I figured it out. It was aggregation issue on my side.

**Comment by paololucente** [comment]
Great to know. I've in any case just committed a patch to be able to debug messages sent over the (RabbitMQ, Kafka) broker. This would allow to pin point whether the issue is on the pmacct side of the things or rather on the library (or use of the library in pmacct) or the broker iteself:

https://github.com/pmacct/pmacct/commit/0c2bd2fb2429f86f6122460ebd0d559418e2ff25
