### ISSUE TITLE
pmacct smtp trafic monitoring using netflow

### ISSUE THREAD

**Issue by AjdinGH** [pmacct/pmacct#143]
Hi,

can anyone help me to solve issue I have.
I need to collect netflow data on smtp port and get notify when someone exceeds the limit.
I need this for monitoring dedicated servers spam so we can block port on core router.
IF you have any idea how to do this please advise, give sam guide how to do this.

Best regards.

**Comment by paololucente** [comment]
Hi @AjdinGH , given the nature of the question, ie. it's more towards building a solution around pmacct rather than a pmacct-specific one, i encourage you to close the issue here and post to the pmacct-discussion list as there you may find somebody that went through something similar and that may be of help to you; you can subscribe here: http://www.pmacct.net/mailman/listinfo/pmacct-discussion . Paolo
