### ISSUE TITLE
Nfacctd json output: event_type, stamp_inserted and stamp_updated

### ISSUE THREAD

**Issue by kaihil** [pmacct/pmacct#145]
Hey,
I am using nfacctd and I just updated pmacct from 1.6.1 to 1.6.2. Now I have three additional fields in my json output:
* event_type
* stamp_inserted
* stamp_updated

I tried to explicitly set `print_markers` to false to turn this off, but it didn't help. (Anyway, I'm not sure if this parameter does what i'm searching for.)

So, is this new behavior a bug or a feature? :)

Thanks and greets!

**Comment by paololucente** [comment]
Hi @kaihil , that change was made with best intentions so i would tend to classify it as a feature :D The move was to uniform a bit JSON (and AVRO) outputs of Kafka, RabbitMQ and print plugins - so that one can move from one to the other and get consistent, same output (at the expense of a bit more verbosity for who comes from the print plugin). Since it's additions (no changes to existing fields), do you see negatives to this? You concerned by the extra verbosity? Thanks, Paolo

**Comment by kaihil** [comment]
If it's intended to be a feature it's all right :) I just wasn't sure if this was intended. I don't have serious concerns, it's just that i have to get rid of these fields now (which is not a big problem). Thanks for you work!
