### ISSUE TITLE
string format of timestamps should follow RFC 3339

### ISSUE THREAD

**Issue by herc6** [pmacct/pmacct#152]
Hello,

I have a question about the used timezone. In the documentation it is mentioned that the timezone of the server wheres pmactt runs should be set to UTC.   I think it is better that the code handles this. It is always possible to ask the timezone and use linux time in the code
Also timestamp_end and timestamp_start  use the timezone that is set on the server and not UTC.  If I use json as output format then the format of these timestamps are "yyyy-MM-dd HH:mm:ss.ss".
 In my opinion you should always use UTC timestamps according to RFC 3339.  The format of timestamp should be  yyyy-MM-ddTHH:mm:ss.ssZ
What do you think ?

**Comment by paololucente** [comment]
Hi, correct me if i'm wrong, i guess you raise two points:

1) timestamp_arrival and, only in case of sFlow, timestamp_start do a gettimeofday() where the timezone argument is NULL; your proposal is to set it explicitly to UTC; true? is there more to it? This is to identify the problem space precisely before commenting;

2) timestamp format should follow RFC3339 when formatted for output (you mention JSON output but i'm pretty sure the same holds for other output formats); i like this proposal and my only comment is we should be a bit careful making it optional for a start: its impact otherwise could be huge given all modern time-series databases use timestamps for ingestion and changing the existing format will screw up at once pretty much all these kind of deployments.

Side question: are you also volunteering to code yourself one or both of these pieces (of course with any support you may need from me, if any is needed)?

Paolo

**Comment by herc6** [comment]
Hello Paolo,

1. concerning use of UTC. I was only referring to Q18 in the FAQS document. First the timezone on my server  was set to CEST/CET. Hence the string format of the timestamps was not UTC but also CEST ( I currently use pmacct with IPFIX) . This gives problems if we switch from summer time to winter time ( I need to do some analytics with this data and aggregate it with other data, where timestamp is UTC).  That is the reason why I propose always to use UTC, even if  the server is set to another timezone.

2.  If we follow RFC3339 then it is easy for other  tools  to get the UTC time from the string format.  You are right that we have to make this optional. 

Concerning your question, I can try to update the code, but I need some time to learn the code. It' s been  a long time ago that I've  programmed  in C.

**Comment by paololucente** [comment]
Hi,

1. I see what happened. I guess it's good to raise awareness on the UTC issue in the FAQS because not all timestamps are under pmacct control: timestamp_arrival, stamp_inserted and stamp_updated are, and could be forced to UTC (although, as i was saying in my previous reply, they are currently not; this may be a good action item for this conversation). But timestamp_start and timestamp_end are not under pmacct control as they are read from flow records - what if the router is set to CET/CEST? Actually, this would be also good to specify as part of that FAQ.

2. Great, we are on the same page on this aspect.

I will review the text in the FAQ (to include the note on the routers) later today and have put action items in my todo list for both points; it may be good for me to handle the first one; as i was saying it would be fantastic if you could make some progress the second one.

**Comment by paololucente** [comment]
Hi, a quick note to say i've managed to make progress on both of the aspects introducing the timestamps_rfc3339 and timestamps_utc kobs. It would be great if you could give it a try to these and confirm working for you; otherwise i'd be just ready to close this issue for the time being. Paolo

**Comment by herc6** [comment]
Hello Paolo,

It works for me.

**Comment by paololucente** [comment]
Thanks for the feedback and hence closing this.
