### ISSUE TITLE
feature request: allow duplication of tables

### ISSUE THREAD

**Issue by oliv3r** [pmacct/pmacct#165]
Currently, we can use sql_table_schema t supply a file with therein a custom database schema.
When wanting to use the supplied sample database however, we'd have to still copy the supplied schema and pass it to the config option. Additionally we have to keep the sql_table variable and the CREATE statement in sync.

Instead, I suggest an additional feature, that uses "CREATE TABLE $sql_table_v$sql_table_version_%Y%m LIKE $sql_table_v$sql_table_version;" to simply copy the main (dummy) table for example

This would reduce the dependency tracking over various files and could potentially remove it all together by some smart parsing as suggested above.

**Comment by paololucente** [comment]
Dear @oliv3r , can you say what is preventing the above to work? Is it the lack of support for $sql_table and $sql_table_version variables as per your example? I mean, should you convert those two variables into fixed strings - which should be acceptable since i guess you don't change name and version often, right? - do you see it working? Or is there a greater issue with the LIKE statement? Paolo
