### ISSUE TITLE
sql_table_schema: read larger files

### ISSUE THREAD

**Issue by citizen-insane** [pmacct/pmacct#169]
Currently a predefined buffer size is set to read the file into, and it is too small to fit even a moderately-sized CREATE TABLE statement.

src/sql_common.c:
`ret = read_SQLquery_from_file(config.sql_table_schema, buf, LONGSRVBUFLEN);`

src/pmacct-defines.h:
`#define LONGSRVBUFLEN (384+MOREBUFSZ)`

src/pmacct.h:
`#define MOREBUFSZ 32`

Therefore the query is limited to 384 or 416 bytes depending on system. Could you instead use a larger buffer or better yet just check the file size and allocate memory accordingly?

**Comment by paololucente** [comment]
Thanks for reporting this. I've opted to increase the buffer size to 8KB, just to be sure, rather than going for reading the file size - which is another simple approach. Rationale was that one can then feed a garbage file GBs large and make damage - or, of course, things should be made slightly more careful and complex than that. Paolo

**Comment by citizen-insane** [comment]
Using this fix I was getting:

ERROR ( default_mysql/mysql ): PRIMARY 'mysql' backend trouble.
ERROR ( default_mysql/mysql ): The SQL server says: Query was empty

Appeared to be fixed by changing line 3202 in sql/sql_common.c:
`handle_dynname_internal_strings_same(buf, LONGSRVBUFLEN, tmpbuf, prim_ptrs, DYN_STR_SQL_TABLE);`
to
`handle_dynname_internal_strings_same(buf, LARGEBUFLEN, tmpbuf, prim_ptrs, DYN_STR_SQL_TABLE);`

**Comment by paololucente** [comment]
Hi @citizen-insane , awww, thanks for the note and sorry for the overlook. Fixed. Paolo
