### ISSUE TITLE
The print plugin in nfacctd does not show nDPI classes passed by pmacctd

### ISSUE THREAD

**Issue by jbrjake** [pmacct/pmacct#177]
I have pmacctd v1.7.0 displaying nDPI-derived classes with the print plugin and it works great, printing out classes like 'Unknown/SSH', 'Unknown/MDNS', etc. But when I send the same data through the nfprobe plugin using netflow v9 format, the nfacctd instance on the other side only shows the class as 'Unknown' or 'unknown'.

Edit: I thought there was a problem with passing through #defines but I was wrong.

**Comment by paololucente** [comment]
Hi @jbrjake , thanks for reporting this. I will reproduce in my testbed. Meanwhile what would help is if you could send me (here or by unicast email) a capture in libpcap format of the packets produced by the nfprobe plugin. Paolo

**Comment by jbrjake** [comment]
Thanks Paolo! Here's a pcap dump. Looking at it in Wireshark, I think maybe the app_protocol isn't getting sent by nfprobe, just the master protocol?
[nfprobe.pcap.zip](https://github.com/pmacct/pmacct/files/1601277/nfprobe.pcap.zip)

**Comment by paololucente** [comment]
Thanks for the trace. It actually looks the issue is nDPI classes are not exported as NetFlow Option Data packets - and they should be. I found this to be related to "class 0", as you can see in the commit above. Can you please give master code a try and let me know? On a different note: you are right only one protocol is exported, actually the app_protocol, which is the one i see being populated by nDPI, IS exported and the master_protocol, which i find being almost always zero, IS NOT exported. Shall we find that we want both in future, a small patch is going to be required. Paolo

**Comment by jbrjake** [comment]
Thank you so much! :) Built from the master branch and now I'm seeing the app_protocols in nfacct. I've noticed the same thing with the master_protocol being pretty useless, so I'm quite happy with just having the app name :)
