### ISSUE TITLE
Support newer mongo-c-driver

### ISSUE THREAD

**Issue by hydrapolic** [pmacct/pmacct#187]
Please make it possible to use newer mongo-c-driver. The build fails when using something recent:

````
checking whether to enable PostgreSQL support... no
checking whether to enable MongoDB support... yes
checking for MONGODB... no
checking default locations for libmongoc... not found
checking for mongo_connect in -lmongoc... no
configure: error: 
                        ERROR: missing MongoDB library (0.8 version). Refer to: https://github.com/mongodb/mongo-c-driver-legacy
````

https://bugs.gentoo.org/518624

**Comment by paololucente** [comment]
Dear Tomas,

Thanks very much for this. Actually the current plans for version 1.7 are to slowly phase out the MongoDB plugin due to the apparent lack of interest/community around it. I'd leave this issue open so to invite anybody else interested to see this happening to show interest by giving a +1 to this. 

Paolo

**Comment by tongorz** [comment]
> Dear Tomas,
> 
> Thanks very much for this. Actually the current plans for version 1.7 are to slowly phase out the MongoDB plugin due to the apparent lack of interest/community around it. I'd leave this issue open so to invite anybody else interested to see this happening to show interest by giving a +1 to this.
> 
> Paolo

Time series collection are natively supported and optimized for storing and working with time-series data by MongoDB 5.0. 
It would be great if pmacct can push netflow or bgp/bmp data to mongo directly.
