### ISSUE TITLE
Is it possible to change order of aggregate result?

### ISSUE THREAD

**Issue by anacondaaa** [pmacct/pmacct#208]
Hello,
I am using pmacct with aggregate line like this.

'aggregate: peer_src_ip, src_host, src_port, dst_host, dst_port, proto, src_mac, dst_mac, tcpflags'

I want to have peer_src_ip at first column, but when i get the result, order isn't what I expected.

It is like,

'SRC_MAC,DST_MAC,PEER_SRC_IP,SRC_IP,DST_IP,SRC_PORT,DST_PORT,TCP_FLAGS,PROTOCOL,PACKETS,BYTES'.

Is there any option for this order issue?

Thank you for your great tool.

**Comment by paololucente** [comment]
Dear @anacondaaa , thanks for your kind words. I can confirm that the ordering is fixed and not reflecting the order in the 'aggregate' primitive. You may switch to JSON which is a self-describing format so that 1) inherently ordering is less than an issue and 2) you have libraries in several languages by which you can access elements of the JSON as hash by their key. Paolo

**Comment by anacondaaa** [comment]
Oh Thank you for the comment!
