### ISSUE TITLE
No output_file when no traffic data

### ISSUE THREAD

**Issue by anacondaaa** [pmacct/pmacct#209]
Hi @paololucente.
I have another question.

When I used 0.14.3 version with config like,

print_refresh_time: 60
print_output:csv
print_time_roundoff: m
print_output_file: ~/data/pmacct/data-%Y%m%d-%H%M.txt

It always created file whether captured traffic data or not. (file with only aggregate headers when no traffic data)

Now I use 1.7.1 version with config like this,

print_refresh_time: 60
print_output:csv
print_history: 60
print_history_roundoff: m
print_output_file: ~/data/pmacct/data-%Y%m%d-%H%M.txt
print_output_file_append: true

It only creates file when there is captured traffic data. It doesn't create file when no traffic data captured.

I want pmacct to create files every minutes like previous version.
Is there any config option or solution for solve my issue?

thank you.

**Comment by paololucente** [comment]
Hi @anacondaaa , this is one of the rare cases in which a developer can be satisfied with the documentation he has written :) I mean to say, this change was documented as part of the UPGRADE document: https://github.com/pmacct/pmacct/blob/1.7.1/UPGRADE#L397-L406 . As you may read, this was done to bring consistency among plugins - so that now they all behave the same. Would you have a solid use-case for this feature request? Paolo

**Comment by anacondaaa** [comment]
Thanks for clarifying. :)
In my case, I use pmacct and sflow agent with own monitoring tool by parsing output file.
In previous version, I could notice sflow agent is dead when monitoring tool sends notification caused by file not found Exception.

In brief,
no file = sflow agent has some problem.
empyt file = no traffic to account for.

I respect your decision but, can you consider adding option for this issue?
Thank you.

**Comment by anacondaaa** [comment]
Hi @paololucente.
I think your suggestion is acceptable.
I will change my logic like that.
thanks for feedback!
