### ISSUE TITLE
print plugin not working on 1.7.1

### ISSUE THREAD

**Issue by blahu** [pmacct/pmacct#213]
Paolo,

I have a problem with v1.7.1 and print plugin.

running on version 1.6.0 - everything was ok

Config file
```

sfacctd_renormalize: true
plugins: print
aggregate: peer_src_ip, src_net, src_mask, proto, src_port, dst_port, in_iface, out_iface
print_output: csv
print_num_protos: true
print_output_file: /var/log/pmacct/%Y/%Y-%m/%Y-%m-%d/$peer_src_ip-sflow-%Y%m%d-%H.json
print_output_file_append: true
print_latest_file: /var/log/pmacct/$peer_src_ip-sflow-latest
print_history: 60m

```

resulting output file for peer_src_ip==x.x.x.127, contains only records for x.x.x.127

```
x.x.x.127,21,1000091,a.a.a.0,26,10130,41155,6,21845,1398080
x.x.x.127,21,0,0.0.0.0,0,59025,60100,17,21845,2206345
x.x.x.127,21,0,0.0.0.0,0,1988,20004,17,21845,1944205
x.x.x.127,20,0,0.0.0.0,0,64069,64069,17,21845,9917630
```

after upgrading to 1.7.1, using the same config file, $peer_src_ip is not honoured and file for x.x.x.127 also contains data from other sflow peers. It does create separate files for each encountered $peer_src_ip, but all files have the same data in it (records from all peers)

separately to that, if I change to json output the aggregates are not honoured as well and following fields are present:

`{"event_type": "purge", "peer_ip_src": "x.x.x.x", "iface_in": 33, "iface_out": 0, "net_src": "0.0.0.0", "mask_src": 0, "port_src": 64032, "port_dst": 64032, "ip_proto": 17, "stamp_inserted": "2018-07-17 11:20:00", "stamp_updated": "2018-07-17 11:21:01", "packets": 109225, "bytes": 49588150}`

```
sFlow Accounting Daemon, sfacctd 1.7.1-git (20180331-00+c3)

Arguments:
 '--exec-prefix=/usr' '--mandir=/usr/local/man' '--enable-jansson' '--enable-l2' '--enable-ipv6' '--enable-64bit' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
libpcap version 1.5.3
jansson 2.11

System:
Linux 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.
```

any ideas?

UPDATE 1, I have tested each release between 1.6.0 and 1.7.1 and all failed. Only 1.6.0 works as expected - there is separated file for each peer_src_ip and json file contains all the aggregates listed.

**Comment by paololucente** [comment]
Hi @blahu ,

We have a bit of a problem: i can't reproduce any of the two issues you are reporting. I tried both CSV and JSON encodings, with and without appending, same directory structure and file naming as yours - nothing.

While it is true i'm using master code, nothing should have really changed since 1.7.1 on any of the aspects involved.

We should get more in sync and to do so I propose: 1) you use master code here on GitHub (so that we are testing the same code) and 2) you send me (your choice if here or via unicast email) a pcap file with some sFlow traffic from different agents so that we can both replay it with the -I (capital India) command-line knob and hence reason on the very same input.

Let me know if this can work for you.

Paolo

**Comment by blahu** [comment]
I have switched to master code now.
After experimenting a lot, I have noticed that when I comment out latest file option, everything works as expected.
I will try to unicast you a pcap tomorrow.
