### ISSUE TITLE
tcpflags aggregation sums flags

### ISSUE THREAD

**Issue by pawmal** [pmacct/pmacct#254]
It seems pmacct logically sums TCP flags using one entry when using `tcpflags` aggregation, instead of creating multiple flow entries.

As a result, single entry typically reports counter as "SYN+ACK+PSH" or "SYN+ACK+PSH+FIN" or "ACK+PSH+FIN" or "ACK+PSH+RST" which is misleading (e.g. 1 packet was SYN, 999 were ACKs, `pmacct` reports 1000 "SYN+ACK" packets, I would rather expect 2 separate counters here). In the long term, all TCP flows tend to become `tcpflags=31` which is:
```
>>> TCP(flags=31)
<TCP  flags=FSRPA |>
```

As a workaround one could probably use `aggregate_filter` and multiple tables to split SYN an non-SYN traffic accounting.

I believe this behaviour should at least be documented somewhere.

```
# pmacct -p /tmp/foo.pipe -c dst_net -M '*'|sort -k3|grep tcp
30          0           x.y.z28.0                                  24        31         tcp         51069500              65949607500
30          0           x.y.z29.0                                  24        18         tcp         1010500               41436000
30          0           x.y.z30.0                                  24        18         tcp         941500                38244000
30          0           x.y.z31.0                                  24        22         tcp         948500                38702000
[...]
30          0           2001:xxx::                                     33        31         tcp         113624000             146952937500
30          0           2001:xxx:x000::                                33        22         tcp         50000                 3710000
```

**Comment by paololucente** [comment]
Hi Pawel,

Thanks for your note. You are right the behaviour may come unexpected if one has not dealt with NetFlow/IPFIX before and I tried documenting this, see the commit above. It also explains the magic passage why it behaves like that and what could be done in order to achieve a TCP flags analysis behaviour (like you said, this can be done with aggregate_filter or using a filter in pre_tag_map, assigning tags per flags/flag combinations and hence effectively de-aggregating as wanted. 

Let me know if this is sufficient. Feel free to contribute with further text or an example.

Paolo
