### ISSUE TITLE
SO_REUSEPORT with nfacctd_allow_file

### ISSUE THREAD

**Issue by ccakes** [pmacct/pmacct#272]
I have an existing deployment using nfacctd to collect Netflow and pmbgpd to collect BGP data. I have a few nfacctd processes running using SO_REUSEPORT to balance the load and better handle the output.

I'm trying to add the `bgp_daemon` thread to enrich the flow data along with `bgp_daemon_allow_file` and `nfacctd_allow_file` to "pin" routers to specific collector processes. Basically just following the instructions [here](https://github.com/pmacct/pmacct/blob/8afa6284f44c46f28df9d6cd23d61790dc48d2d1/QUICKSTART#L1704). As soon as I configure the allow maps though I see a huge drop in the number of flows collected - it's only recording ~10-15% of the total.

I'm running 10 processes so at at a guess it sounds like OS is handing a packet to a random nfacctd process based on it's own load-balancing, then nfacctd is either accepting or rejecting the packet depending based on that processes allow_file. If nfacctd rejects, then the flow datagram is lost? I eventually get all the BGP sessions up but that fits in with the routers just retying until they hit the right process.

I assume I'm missing something obvious or is this config not actually expected to work? Should the datagram be requeued by the OS and delivered to another socket? That doesn't sound right either..

Is the suggested architecture here to run a tee layer in front and use tee_receivers + pre_tag_map to distribute the datagrams to the right collector processes? I don't really want to have to listen on multiple UDP ports, it feels like there should be a better way.

**Comment by paololucente** [comment]
Hi Cameron,

Thanks for getting in touch. SO_REUSEPORT performs balancing but it is totally disconnected from the application; this, in our context, makes it suitable for balancing BGP sessions (because, as you say, give it a very few retries and all routers will connect to the expected collector) but not NetFlow v9/IPFIX packets (because it's a template-based mechanism and that would require collectors to exchange received templates). So, as you conclude, yes, for NetFlow v9/IPFIX you need a layer of replication (tee plugin) in front. 

I have this setup in place myself, and works great for me. Relatively simple and suitable to scale out as wanted. To take up all BGP sessions, true, it can take few minutes but restarting the daemon once in months i find it an acceptable bargain for the simplicity of the architecture.

Paolo

**Comment by paololucente** [comment]
(and by re-reading the documentation section you pointed i agree there is a mistake, ie. two daemons listen on the same port for flow messages; i will fix that asap)

**Comment by ccakes** [comment]
Fantastic, the new config seems to be working perfectly. Cheers for the help!
