### ISSUE TITLE
Question: Quickstart guide to setup a NetFlow/IPFIX/sFlow replicator

### ISSUE THREAD

**Issue by Boes-man** [pmacct/pmacct#288]
Hello, I am looking to use pmacct for netflow uses. Just starting on the track and for now want to use pmacct to forward netflow traffic to an Elastic Logstash forwarded. Some like install on a centos server and then pmacct forwarding all traffic on that centos host's eth0 to a forward collector, eg ip:port of logstash.

I see the quick start for it, but still don't know how to start :| Thanks

**Comment by paololucente** [comment]
Hi @Boes-man , can you be more specific? Like: what document you are reading, where you got stuck or what is not clear or what you would need to start? It seems you need to read "Quickstart guide to setup a NetFlow/IPFIX agent/probe" of QUICKSTART document rather than the replicator section: probe is to generate NetFlow traffic listening on a given interface (which i understand is what you want); replicator is to copy NetFlow traffic, say, from routers to different collectors. Paolo
