### ISSUE TITLE
buffer overflow warning seen during build

### ISSUE THREAD

**Issue by mayafox** [pmacct/pmacct#323]
System is ubuntu 18.04, 
configure flags are --enable-kafka --enable-janssen

make
make[2]: Entering directory '/home/user/pmacct/src'
....<normal output with some warnings about unused attributes>....
   CC       sfacctd.o
In file included from /usr/include/string.h:494:0,
                 from pmacct.h:38,
                 from sfacctd.c:23:
In function ‘memcpy’,
    inlined from ‘SF_find_id’ at sfacctd.c:2089:5:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:10: warning: ‘__builtin___memcpy_chk’ writing 16 bytes into a region of size 8 overflows the destination [-Wstringop-overflow=]
   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       sflow.o
  CC       sfv5_module.o
  CCLD     sfacctd

**Comment by paololucente** [comment]
Hi @mayafox , thanks for your report. To reassure this is totally harmless since it's a copy of an IPv6 address from one v6 structure to the other; thing is the v6 structure is chopped in 2x 8 bytes contiguous areas - hence the overflow warning. I am closing this one but also a question to you: is this the only place in the code you get this warning? That would be curious because the same practice is present also in other parts of the code. Paolo

**Comment by mayafox** [comment]
@paololucente Yes this is the only location I saw the warning pop up. Hope that helps
