### ISSUE TITLE
Additional labels

### ISSUE THREAD

**Issue by gandraman** [pmacct/pmacct#332]
Hello,

is it possible to use aditional labels (e.g. label2), like it is possible to use tag and tag2?
Also is there any limit in length of pretag.map file (number of lines, number of set_tag, set_tag2, set_label lines)?

Thanks!
Regards, Dragan

**Comment by paololucente** [comment]
Hi Dragan ( @gandraman ), great to read from you. No, there is no label2 / set_label2 like for tags mainly because you can stack multiple labels in the same field (that one can't do with tags). Can you say what would be your use-case for a label2? And, yes, there are adjustable limits to the pre_tag_map file: maps_row_len (line length) and maps_entries (numer of lines); there is instead no specific limit for directives, ie. set_tag, set_label, etc. Paolo

**Comment by gandraman** [comment]
Hi Paolo,

I apologize for somehow missing this email. We had an idea to put some
additional information received via DNSFlow into pretag.map in order to try
to track applications/services (e.g. youtube, netflix...) and update
pretag.map each few minutes with fresh data, but that would have been very
hard to achieve, if even possible, so we gave up on that and decided just
to collect DNSFlow data independently.

Thank you so much for always responding promptly to any questions, unlike
me answering sometimes.

Kind regards, Dragan
