### ISSUE TITLE
bgp_daemon_lg in nfacctd mode

### ISSUE THREAD

**Issue by ccakes** [pmacct/pmacct#347]
..or something similar. I'm looking for a way to query (or programmatically dump) the RIB state from a running nfacctd process. `bgp_table_dump` doesn't really achieve what I'm after as I'd like to be able to get current state based on an external trigger.

I've had a look through the config options but I don't think there's a combination that gets me all the way. I could dump more frequently but files/pipes aren't really up to that task and I'm trying to avoid the extra infrastructure around Rabbit/Kafka

I'm not sure a combination of xconnects will work either as then the "passthrough" nfacctd process doesn't know about the RIB for enriching flows?

I assume that the lg function isn't allowed in nfacctd because of performance reasons. The actual data I'm after isn't really impacted by as_radius settings or community stripping so if it's for those reasons, would you be open to allowing the lg process on nfacctd with some caveats in the docs?

**Comment by paololucente** [comment]
Hi Cameron ( @ccakes ), 

The Looking Glass feature seems precisely what you are looking for - you are right x-connects won't buy you anything.

To be frank, wiring the LG feature to nfacctd (or better, its BGP thread) is not a biggie - it's not there just as i wanted to gather interest in something like that ( .. and here you are! :-)). So as each piece is in its own thread, let me reassure there would not be a performance hit.

This all said, I can converge pretty quickly on this: would sometime (towards the end of) next week work? 

Paolo

Paolo

**Comment by ccakes** [comment]
Hey Paolo - that'd be awesome! Would appreciate that immensely!

**Comment by paololucente** [comment]
Hi Cameron ( @ccakes ), 

Apologies this took slightly longer than anticipated, part of the issue is that i ran into a bug in the underlying ZMQ part that was introduced sometime last July and that now needs to be backported also to 1.7.4 before it gets released. In any case: this is done and i tested it working in a lab environment; it would be great if you could give it a try and let me know if it works for you. Essentially bgp_daemon_lg and bgp_daemon_lg_* got wired to nfacctd, sfacctd, etc. 

Paolo

**Comment by ccakes** [comment]
Cheers! I'll run it up this week and let you know how it goes 👍
