### ISSUE TITLE
pmacct  proxy-convert 

### ISSUE THREAD

**Issue by avbg** [pmacct/pmacct#390]
Hello.
 Is it possible to collect trafic from hardware in netflow format via pmacct and send it further in sflow format to other collector?

**Version**
nfacctd -V
NetFlow Accounting Daemon, nfacctd 1.7.2-git (20181018-00+c3)

**Comment by paololucente** [comment]
Hi @avbg ,

Once upon a time there was a feature in that sense. NetFlow to sFlow and vice-versa. The feature has been removed by the code base some 10 years ago due to the complexity of maintaining a sane quality of conversion among the matrix of the different protocol versions - and there are no plans to re-introduce it. You may get the last version with the feature here:

http://www.pmacct.net/pmacct-0.12.1.tar.gz

Indeed it's a version of 10 years ago and hence unsupported. But on the other hand it may be that it just works for you. I am going to close this issue.

Paolo
