### ISSUE TITLE
src/util.c fails to build on i386 FreeBSD due to type mismatch in line 1595

### ISSUE THREAD

**Issue by opsec** [pmacct/pmacct#398]
Building 1.7.4p1 on FreeBSD i386 platforms fails with this:

util.c:1595:31: error: format specifies type 'unsigned long' but the argument has type 'size_t' (aka 'unsigned int') [-Werror,-Wformat]
    config.name, config.type, size);
                                            ^~~~

**Comment by paololucente** [comment]
Hi @opsec ,

Thank you for reporting this. It seems a bit harsh refusing to compile for an 'innocent' type mismatch (light pun): can you reassure me you were compiling with --enable-debug on?

As you may have seen, i just passed a commit to address the issue; i tried on a couple of platforms and compilers and '%zu' seems portable. Can you try latest code (or applying the patch to 1.7.4p1) and confirm it working for you?

If you were using --enable-debug and if this patch fixed your issue: can you run a full compiling through --enable-debug so to see we would have other small fixes like these to perform in order to compile cleanly?

Thanks,
Paolo

**Comment by opsec** [comment]
Thanks for the patch. Yes, this fix is working. I now build with --enable-debug and the problem is that a fix for i386 causes a bug for 64bit/amd64/x86_64. I'll dig into this and report back.

**Comment by paololucente** [comment]
Thank you, much appreciated. Look forward.

**Comment by opsec** [comment]
These are the errors building on amd64 with the patches that follow applied:

sql_common.c:129:35: error: format specifies type 'unsigned int' but the argument has type 'unsigned long' [-Werror,-Wformat]
        config.sql_cache_entries, ((config.sql_cache_entries * sizeof(struct db_cache)) +
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

pmacct.c:3783:49: error: format specifies type 'int' but the argument has type 'time_t' (aka 'long') [-Werror,-Wformat]
    if (usec) snprintf(buf, buflen, "%d.%.6ld", tv->tv_sec, (long)tv->tv_usec);
                                     ~~         ^~~~~~~~~~
                                     %ld
pmacct.c:3784:38: error: format specifies type 'int' but the argument has type 'time_t' (aka 'long') [-Werror,-Wformat]
    else snprintf(buf, buflen, "%d", tv->tv_sec);
                                ~~   ^~~~~~~~~~
                                %ld
2 errors generated.
*** [pmacct.o] Error code 1

**Comment by opsec** [comment]
Patches see https://people.freebsd.org/~pi/pm-patches.tar

**Comment by opsec** [comment]
So the problem seems to be: We either have a 64bit value and formatstrings for it or 32bit values and formatstrings for it. It's some type inconsistency. I had no time to dig deeper into this.

**Comment by paololucente** [comment]
Hi @opsec ,

I should have fixed the first error. The other two appear already fixed in master (and 1.7.5 branch). 1.7.5 will be out almost imminently: may i ask you to try compiling 1.7.5 branch plus the two patches associated to this issue and see where we stand? 

Also, if more issues pop up may i ask if we can make it less random shooting? For example: i am fixing things knowing i am not breaking anything - but ultimately i am blind since i don't have a i386 to test on; and i miss an "holistic view" of how much we need to fix (and which platform, which compiler, etc.); at this propo i am not clear whether after the first patch we are making progress or not or moving sideways. 

I understand time is limited so i will propose a one easy procedure for the issue we are hitting: as you encounter new issues, please collect them and comment the relevant lines of code out so that you get to the next issue and we can make upfront a collection of all of them; if you test different versions / platforms / etc. try to sort them out for me.

Paolo

**Comment by paololucente** [comment]
Hey @opsec ,

I was wondering whether there were any news on this? 

Paolo
