### ISSUE TITLE
Huawei netstream renormalization

### ISSUE THREAD

**Issue by danyrlz** [pmacct/pmacct#431]
I would like to report nfacctd_renormalize malfunction with Huawei netstream.
The switch is HUAWEI S6730-H48X6C / SW version V200R019C00SPC200.
Here is the netstream config:

**Global:**
ip netstream timeout active 1
ip netstream timeout inactive 5
ip netstream export version 9
ip netstream export source <IP>
ip netstream export host <IP> 2100 vpn-instance <VPN>
ip netstream export template timeout-rate 1
ip netstream record test
ip netstream export index-switch 32

**Per interface:**
 ip netstream inbound
 ip netstream sampler fix-packets 2000 inbound
 port ip netstream record test inbound

Tested with pmacct 1.6.2 and 1.7.6-git (20200929-0 (85d78cc)) with the same result.
With other equipment like Juniper MX renormalization works fine.
Here are shots from the Huawei dumps:
Would you like me to send privately the Huawei and Juniper dumps?

![image](https://user-images.githubusercontent.com/14218871/95168194-9f6d0b80-07b9-11eb-959b-e52c795c9c72.png)

![image](https://user-images.githubusercontent.com/14218871/95168260-b875bc80-07b9-11eb-9097-fdff6216ac0b.png)

**Comment by paololucente** [comment]
Hi @danyrlz ,

Yes, please. Send me only a Huawei capture in pcap format so that i can replay it locally. Two things: 1) sampling information in NetFlow v9 / IPFIX is exported by means of Options Data packets: you must be sure that these packets are exported to the collector and, in turn, at least one is included in the pcap trace you are going to send me; 2) i already see a potential issue: the typical way sampling works is by having a sampler_id field in Data packets (and above i don't see one!) and this is correlated to the Options Data packet i was referring to which essentially instructs how to map the id to a sampling rate (and potentially other sampling characteristics).

Paolo

**Comment by paololucente** [comment]
Summarizing here the findings so far: it is confirmed that flows do not include a sampler ID. Even more, apparently Option Data containing sampling information is not sent over. For cases like these - especially in heterogeneous networks - the use of a sampling_map is adviced to define the sampling rate for certain devices.
