### ISSUE TITLE
nfacctd not getting the VLAN ID - Netflow V9

### ISSUE THREAD

**Issue by ronaldocz** [pmacct/pmacct#438]
Hi there, I'm not being able to get the VLAN ID, it's always VLAN 0.

Looks like this the same problem mentioned here https://pmacct-discussion.pmacct.narkive.com/DI5vSA0L/nfacctd-not-decoding-vlan-id#selection:2.645.5 however the link mentioned in the solution is not working for me. I'm using netflowV9

this is my conf:
#########
debug: true
plugins: print[print]
aggregate: vlan, src_host, dst_host, timestamp_start, timestamp_end, src_port, dst_port, proto

 print_output_file[print]: /tmp/5m_avg.json
 print_output[print]: json
 print_history[print]: 1m
 print_history_roundoff[print]: m
 print_refresh_time[print]: 30
 print_trigger_exec[print]: /opt/pmacct/pmactt2influx.sh
#################

{"event_type": "purge", "vlan": 0, "ip_src": "157.240.3.20", "ip_dst": "10.1.31.41", "port_src": 443, "port_dst": 51348, "ip_proto": "tcp", "timestamp_start": "2020-10-30 11:19:16.000000", "timestamp_end": "2020-10-30 11:21:28.000000", "stamp_inserted": "2020-10-30 11:19:00", "stamp_updated": "2020-10-30 11:21:32", "packets": 29, "bytes": 2080}
{"event_type": "purge", "vlan": 0, "ip_src": "157.240.3.54", "ip_dst": "10.1.30.167", "port_src": 443, "port_dst": 54878, "ip_proto": "tcp", "timestamp_start": "2020-10-30 11:19:15.000000", "timestamp_end": "2020-10-30 11:21:25.000000", 

Thank you.
Ronaldo

**Comment by paololucente** [comment]
Hi Ronaldo (@ronaldocz ),

I can unfortunately say little about the issue without looking at your actual NetFlow v9 data. It could be VLAN is not included in your NetFlow export, it could be there is some issue with encoding/decoding. Please do such inspection yourself or feel free to send me privately a pcap trace of your NetFlow.

If you decide to create a pcap trace: https://github.com/pmacct/pmacct/blob/1.7.5/QUICKSTART#L2902-#L2914 . In order to make a readable trace for NetFlow v9/IPFIX you must be sure to capture the templates as well - as they are needed to decode the actual data packets. Before sending the trace over you can try to replay it locally as a savefile to check it is readable.

Paolo

**Comment by ronaldocz** [comment]
Thank you for your response, I'll take a look at the flow today.
