### ISSUE TITLE
Using pmacct for passive speed logging

### ISSUE THREAD

**Issue by lokkju** [pmacct/pmacct#447]
I'm trying to have a passive throughput monitor for all clients; essentially, log the average and max bits per second usage of each client downloading from my server (I'm running this on said server). My current approach, using pmacctd, is to use `print_refresh_time` set to `1` and write to a named pipe; then have a script reading from that named pipe, and writing aggregated counters to a database table.

Is there a more efficient or just less hacky way to do this? I specifically care about logging the average and max bps rate per remote IP that is connecting to my server. `*_history` doesn't seemed designed for this kind of aggregation, but avg/max throughput speed in bps seems like it would be a common use case, so I feel I might be missing something.

**Comment by paololucente** [comment]
Hi @lokkju ,

The conversion from bytes to bps is not being performed by pmacctd so, yes, the simple bits of math are part of post-processing. pmacct does "only" the time bucketing (which is the `*_history` setting). Then, in order to have avg/max bps, you want to perform a second level of time bucketing where you take values from the first level time buckets (those provided by pmacctd) and elect your average, maximum, etc. This is also part of the post-processing - understandably, i would say - as it keeps the exercise flexible, you have the first level bucket data then you can compute avg/max on any time window as you wish.

With the above framework defined, please explain me better the hacky point. Is it because of passing through files / stdout via the print plugin? Is it that you don't like the concept of streaming pipeline and/or post-processing? 

Paolo

**Comment by lokkju** [comment]
My understanding from the documentation and from experimenting was that *_history only supports increments of one minute or greater?

**Comment by paololucente** [comment]
Hi @lokkju ,

Yes Sir, that is correct.

Should you want to go to the sec or usec resolution, forget `*_history` directive: do instead `aggregate: <your primitives of interest>, timestamp_start`. timestamp_start will give you the timestamp at the resolution of the library (or if `timestamps_secs: true` is specified, to the second resolution, omitting the residual time).

Paolo

**Comment by lokkju** [comment]
Thanks, that helps me understand the sql aggregation stuff much better. One related question: timestamp_secs doesn't seem to be working with the print/memory plugins. I have `timestamp_secs: true`, but the print plugin is still showing the `timestamp_start` with sub-second precision.

**Comment by paololucente** [comment]
It may be a case of mis-spelling: not `timestamp_start` but `timestamps_start` (see the s in timestamps) and probably it is saying the log that it does not reckon the config directive. Let me know if this is the case.

**Comment by lokkju** [comment]
That was the problem, thanks again; with `timestamps_secs: true`, it makes doing these calculations extremely straightforward.

**Comment by paololucente** [comment]
Wonderful, thanks for confirming. And action point for me: i will document a bit better what we discussed in this issue, ie. how to properly go under 1 minute to second or (typically) usec resolution.
