### ISSUE TITLE
Well known names for tcp_flags

### ISSUE THREAD

**Issue by Slepwin** [pmacct/pmacct#466]
**Description**
It would be great if you add some minor change to nfacctd/sfacctd code for **tcp_flags** and produce well known names like CWR | ECE | URG | ACK | PSH | RST | SYN | FIN. The same mapping already exists for **ip_proto** field.

**Version**
`nfacctd 1.7.5`

**Comment by paololucente** [comment]
Hi Alexander ( @Slepwin ),

Nice idea. I will flag this as Feature Request and give myself a low priority on it. Slight complexity, when put this to work at scale, compared to ip_proto is string manipulation due to the possible appends of flags, ie. say multiple samples contribute to the same flow (aggregate).

Paolo

**Comment by scuzzilla** [comment]
@Slepwin https://github.com/pmacct/pmacct/pull/550

**Comment by paololucente** [comment]
Thanks for pointing that out, Salvatore ( @scuzzilla ).

Alexander ( @Slepwin ), you could look at the code kindly contributed by Salvatore about this `tcpflags_encode_as_array`. It works for both JSON and Avro encoding but not (and no plans to support them in future) CSV and tab-formatted. Hope this does address your Feature Request.

Paolo
