### ISSUE TITLE
Enumeration of numeric IDs to application names.

### ISSUE THREAD

**Issue by skyblaster** [pmacct/pmacct#473]
**Description**
Using the official Docker container as a test base and the following command, I processed a PCAP  with the `class` primitive included:
`$ sudo docker run -v /etc/pmacct/pmacctd.conf:/pmacctd.conf -v /home/jason/feb23_test3.pcap:/test.pcap pmacct/pmacctd pmacctd -f pmacctd.conf -I test.pcap`

```
$ cat /etc/pmacct/pmacctd.conf

daemonize: false
pidfile: /var/run/pmacctd.pid
syslog: daemon
aggregate: src_host, dst_host, src_port, dst_port, proto, tos, class
plugins: nfprobe, print
nfprobe_receiver: 192.168.1.228:9995
nfprobe_version: 9
```
Looking at the resulting NetFlow packets in Wireshark, I see `Classification Engine ID: Unknown` when I suspect it should be 22.

@robcowart has analyzed the problem and reports that the format of the Selector ID is dependent on Classification Engine ID.
pmacct is placing this numeric value into the byte which should contain the Classification Engine ID.

NetFlow PCAP sent by email for reference.

**Version**
Promiscuous Mode Accounting Daemon, pmacctd 1.7.6-git [20201226-0 (7ad9d1b)]

Arguments:
 '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.2
libpcap version 1.8.1
MariaDB 10.3.27
PostgreSQL 110010
sqlite3 3.27.2
rabbimq-c 0.11.0-pre
rdkafka 1.6.1
jansson 2.13.1
MaxmindDB 1.5.2
ZeroMQ 4.3.2
Redis 1.0.1
GnuTLS 3.6.7
avro-c
serdes
nDPI 3.2.0
netfilter_log

System:
Linux 5.9.0-5-amd64 #1 SMP Debian 5.9.15-1 (2020-12-17) x86_64

Compiler:
gcc 8.3.0

**Comment by paololucente** [comment]
Hi @skyblaster ,

Thanks for getting in touch and for following-up by email with the pcap.

You are hitting the same issue described in #428 i believe. Please scroll to the very bottom for the conclusion: pmacct exports application classification for flows similarly to what a Cisco router does with NBAR: flows have a numerical ID; in turn, that ID references a lookup map, ie. ApplicationID -> ApplicationName, exported to the collector via NetFlow / IPFIX Options packets.

Intuitively, you don't want each and every flow to contain a string saying "ssh" or "thisisagreatprotocolname", true? So, all is exported to the collector and the collector should support this mechanism, ie. look up the ID into a Name for the application. Failing to do so, you won't be able to export application information even from a Cisco router, for example.

Paolo

**Comment by skyblaster** [comment]
I understand the process, however I don't have any valid NBAR based flow captures to compare with.

I believe the issue described by Rob is that the Classification Engine ID and Selector ID are not properly encoded in pmacct.
Wireshark shows the Selector ID as 000000
https://www.iana.org/assignments/ipfix/ipfix.xhtml#classification-engine-ids

**Comment by skyblaster** [comment]
Not sure if this helps or not as it is in IPFIX format: https://community.broadcom.com/communities/community-home/librarydocuments/viewdocument?DocumentKey=4ee44f39-12ef-4cc9-a0ed-0b7bc9135082

**Comment by robcowart** [comment]
# Background

@paololucente you are correct that IE 95 (application ID) is an enumeration of actual names. However, application ID is not a simple number value. It is an encoded value containing multiple components. That encoding is specified in [RFC6759, section-4](https://tools.ietf.org/html/rfc6759#section-4).

```text
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
| Class. Eng. ID|         Selector ID  ...                      |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                             ...                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

The format of the Selector ID (`SelectID`) is specific to the Classification Engine ID (`ClassID`).

[RFC6759, section-4.1](https://tools.ietf.org/html/rfc6759#section-4.1) provides valid values for `ClassID`. IANA, which manages [the official registry of ClassIDs](https://www.iana.org/assignments/ipfix/ipfix.xhtml#classification-engine-ids) has since added two additional values. The following table contains the complete list:

ClassID | ClassName | Length | Description
--- | --- | --- | ---
1 | IANA-L3 | 1 | The Assigned Internet Protocol Number (layer 3 (L3)) is exported in the Selector ID. See [https://www.iana.org/assignments/protocol-numbers]. [RFC6759]
2 | PANA-L3 | 1 | Proprietary layer 3 definition. An enterprise can export its own layer 3 protocol numbers. The Selector ID has a global significance for all devices from the same enterprise. [RFC6759]
3 | IANA-L4 | 2 | The IANA layer 4 (L4) well-known port number is exported in the Selector ID. See [https://www.iana.org/assignments/service-names-port-numbers]. Note: as an IPFIX flow is unidirectional, it contains the destination port in a flow from the client to the server. [RFC6759]
4 | PANA-L4 | 2 | Proprietary layer 4 definition. An enterprise can export its own layer 4 port numbers. The Selector ID has global significance for devices from the same enterprise. Example: IPFIX had the port 4739 pre-assigned in the IETF draft for years. While waiting for the RFC and its associated IANA registration, the Selector ID 4739 was used with this PANA-L4. [RFC6759]
6 | USER-Defined | 3 | The Selector ID represents applications defined by the user (using CLI, GUI, etc.) based on the methods described in section 2. The Selector ID has a local significance per device. [RFC6759]
12 | PANA-L2 | 5 | Proprietary layer 2 (L2) definition. An enterprise can export its own layer 2 identifiers. The Selector ID represents the enterprise's unique global layer 2 applications. The Selector ID has a global significance for all devices from the same enterprise. Examples include Cisco Subnetwork Access Protocol (SNAP). [RFC6759]
13 | PANA-L7 | 3 | Proprietary layer 7 definition. The Selector ID represents the enterprise's unique global ID for the layer 7 applications. The Selector ID has a global significance for all devices from the same enterprise. This Classification Engine Id is used when the application registry is owned by the Exporter manufacturer (referred to as the "enterprise" in this document). [RFC6759]
18 | ETHERTYPE | 2 | The Selector ID represents the well- known Ethertype. See [http://standards.ieee.org/develop/regauth/ethertype/eth.txt]. Note that the Ethertype is usually expressed in hexadecimal. However, the corresponding decimal value is used in this Selector ID. [RFC6759]
19 | LLC | 1 | The Selector ID represents the well-known IEEE 802.2 Link Layer Control (LLC) Destination Service Access Point (DSAP). See [http://standards.ieee.org/develop/regauth/llc/public.html]. Note that LLC DSAP is usually expressed in hexadecimal. However, the corresponding decimal value is used in this Selector ID. [RFC6759]
20 | PANA-L7-PEN | 3 | Proprietary layer 7 definition, including a Private Enterprise Number (PEN) [https://www.iana.org/assignments/enterprise-numbers] to identify that the application registry being used is not owned by the Exporter manufacturer or to identify the original enterprise in the case of a mediator or 3rd party device. The Selector ID represents the enterprise unique global ID for the layer 7 applications. The Selector ID has a global significance for all devices from the same enterprise. [RFC6759]
21 | Qosmos ixEngine | 4 | The Selector ID contains an application ID from the Qosmos ixEngine.
22 | ntop nDPI | n | The Selector ID contains a protocol from the ntop nDPI engine.

Obviously that last one in the list is particularly interesting for _pmacct_ as it is using _nDPI_, but we will come back to that.

Let's look at a few examples...

First is a PCAP from Cisco SD-WAN equipment. This is the template for the option data:

```text
Set 1 [id=3] (Options Template): 257
    FlowSet Id: Options Template (V10 [IPFIX]) (3)
    FlowSet Length: 22
    Options Template (Id = 257) (Scope Count = 1; Data Count = 2)
        Template Id: 257
        Total Field Count: 3
        Scope Field Count: 1
        Field (1/1) [Scope]: APPLICATION_ID
            0... .... .... .... = Pen provided: No
            .000 0000 0101 1111 = Type: APPLICATION_ID (95)
            Length: 4
        Field (1/2): APPLICATION_NAME
        Field (2/2): APPLICATION_DESC
```

We can see here IE 95, the Application ID. In an example of the record we have a value of `0d 00 04 d9`. This value is not simply the number `218105049`. It must be **_decoded_**.

As shown above the first byte is the `ClassID`. `0d` is `13`, which from the table we see is PANA-L7, a 3-byte `SelectID` value for a private enterprise-defined application. Those three bytes from the example are `00 04 d9`, or `1241`. Using the convention from RFC6759  to separating the component values of the application id with `..`, the correct decoded value of this application ID is `13..1241`. From Wireshark we see:

```text
Flow 12
    Classification Engine ID: PANA-L7 (13)
    Selector ID: 0004d9
    ApplicationName: tumblr
    ApplicationDesc: Tumblr is a microblogging and social networking website

```

There is a weakness to using the PANA-L7 (13) `ClassID`. If option data is not received which contains the mappings, a static mapping must be used. However there is no way to know which vendor's mappings should apply here. Fortunately a vendor can send Application IDs using `ClassID` PANA-L7-PEN (20) encoding. This is increasingly becoming the standard, with vendors such as Fortinet, Velocloud and others adopting this `ClassID`. Let's look at example from Fortinet:

```text
FlowSet 3 [id=1] (Options Template): 257
    FlowSet Id: Options Template(V9) (1)
    FlowSet Length: 32
    Options Template (Id = 257) (Scope Count = 1; Data Count = 4)
        Template Id: 257
        Option Scope Length: 4
        Option Length: 16
        Field (1/1) [Scope]: System
        Field (1/4): APPLICATION_ID
            Type: APPLICATION_ID (95)
            Length: 9
        Field (2/4): APPLICATION_NAME
        Field (3/4): APPLICATION_DESC
        Field (4/4): applicationCategoryName
    Padding: 0000
```

We again see here IE 95, so we must again follow the encoding rules from RFC6759. In an example from Fortinet we have the value `14 00 00 30 44 00 00 81 1d`.

Again we look at the first byte to get the `ClassID`, which is `14` (decimal `20`) for PANA-L7-PEN. Now it gets a little confusing. We see the length in the table is 3, but the data contains 8 bytes. Part of the reason for this is described in [RFC6759, section-4.2](https://tools.ietf.org/html/rfc6759#section-4.2). It states:

>There are an extra 4 bytes for the PEN.  However, the PEN is not considered part of the Selector ID.

So the first 4 bytes after the `ClassID` indicate the PEN (Private Enterprise Number) of vendor which is providing the application ID. In our example this is `00 00 30 44`, or `12356`. We can lookup this value in the [IANA registry of Enterprise Numbers](https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers) and see that this PEN is for *_Fortinet, Inc._*

So now we are left with `00 00 81 1d`. But wait! Didn't RFC6759 and the IANA `ClassID` Registry say that the `SelectID` should be 3 bytes? It does. However [RFC6759, section-4.2](https://tools.ietf.org/html/rfc6759#section-4.2) also states that:

>Application IDs MAY be encoded with a larger length.  For example, a normal IANA L3 protocol encoding would take 2 bytes since the Selector ID represents the protocol field from the IP header encoded in one byte. However, an IANA L3 protocol encoding may be encoded with 3 bytes. In this case, the Selector ID value MUST always be encoded in the least significant bits as shown in Figure 2.

```text
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|Class. Eng. ID |zero-valued upper-bits ... Selector ID         |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

Since the `SelectID` is the last bytes in the ID, it is still compliant as a 4-byte, rather than 3-byte, value. This is also why we see in the template that the length for IE 95 is 9, rather than 8.

We can now take the 4-byte value of `00 00 81 1d`, which has a decimal value of `33053`, and assemble our application ID: `20..12356..33053`. 

# The `pmacct` Bug

With that background, let's look at why the application IDs provided by `pmacct` are problematic. In the template sent by `pmacct` we can see that IE 95 is being used for Application ID...

```text
FlowSet 5 [id=1] (Options Template): 4097
    FlowSet Id: Options Template(V9) (1)
    FlowSet Length: 22
    Options Template (Id = 4097) (Scope Count = 1; Data Count = 2)
        Template Id: 4097
        Option Scope Length: 4
        Option Length: 8
        Field (1/1) [Scope]: System
        Field (1/2): APPLICATION_ID
            Type: APPLICATION_ID (95)
            Length: 4
        Field (2/2): APPLICATION_NAME
```

By using IE 95, `pmacct` is effectively entering a contract with the collector which says "the data will be encoded according to RFC6759"

Let's look at what `pmacct` is actually sending. We will use the example `14 00 00 00`. The intention here seems to be that `14` (decimal `20`) should indicate MySQL traffic ([NDPI_PROTOCOL_MYSQL](https://github.com/ntop/nDPI/blob/ea0309d21b168d70b853986a342d08966012d07b/src/include/ndpi_protocol_ids.h#L51)). However the encoding is wrong. Hints of what is going on can be seen in Wireshark. Notice the value of `Classification Engine ID`:

```text
Flow 4
    ScopeSystem: 00000000
    Classification Engine ID: PANA-L7-PEN (20)
    Selector ID: 000000
    ApplicationName: MySQL
```

Here is an expanded set of values which further demonstrate how the improper encoding is problematic:

```text
Flow 7
    ScopeSystem: 00000000
    Classification Engine ID: Unknown (11)
    Selector ID: 000000
    ApplicationName: NFS
Flow 8
    ScopeSystem: 00000000
    Classification Engine ID: PANA-L2 (12)
    Selector ID: 000000
    ApplicationName: SSDP
Flow 9
    ScopeSystem: 00000000
    Classification Engine ID: PANA-L7 (13)
    Selector ID: 000000
    ApplicationName: BGP
Flow 10
    ScopeSystem: 00000000
    Classification Engine ID: Unknown (14)
    Selector ID: 000000
    ApplicationName: SNMP
```

You can see how Wireshark is trying to decode the value into `ClassID` and `SelectID` components, but is getting confused.

This is the same for other collectors. In the example above (`14 00 00 00`). An RFC-compliant collector will pull off the first byte expecting a `ClassID`. In this case it indicates a PANA-L7-PEN. The collector then expects the next 4 bytes to be the PEN, and at least 3 bytes which would be the `SelectID`. However there are only 3 bytes. So this value has to be flagged as corrupt and discarded.

# Fix Options

There are a few things that can be done to correct this issue. All of them have in common that the value provided by nDPI should not in any scenario be used to directly populate the first byte of IE 95. If IE 95 is used, the nDPI ID value would be used for the `SelectID` component.

## Encode as PANA-L7

The encoding would be:

```text
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|    13 (0xD)   |                 nDPI ID value                 |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

`ClassID`: 13 (0xD)
`SelectID`: nDPI ID value

As described earlier this method is less preferred than PANA-L7-PEN.

## Encode as PANA-L7-PEN

```text
 0                   1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|   20 (0x14)   |                      PEN...                   |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|    ...PEN     |                 nDPI ID value                 |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

`ClassID`: 20 (0x14)
`PEN`: The PEN for the source of this application ID
`SelectID`: nDPI ID value

The PEN should probably be 35632 (ntop), but could also be 43874 (pmacct). The reason that I would prefer 35632 is that the `pmacct` team may later adopt alternative DPI libraries, and this could result in conflicts if using 43874.

## Encode as ntop nDPI

Finally we come to what would be, in this case, the MOST CORRECT way to encode the application ID values. It is also the most compact, which is an added benefit.

```text
 0                   1
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|   22 (0x16)   | nDPI ID value |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

`ClassID`: 22 (0x16)
`SelectID`: nDPI ID value

This encoding is compact because the nDPI engine has a short list of detectable apps. Detection for old apps is constantly removed and the IDs reused.

NOTE: There is an open issue looking to provide [immutable nDPI IDs](https://github.com/ntop/nDPI/issues/1072). In this case the length of the ID could change. This however is not an issue as the `SelectID` can be larger as long as the option data template indicates this increased length.

# Summary

Hopefully this provides the context and background necessary to understand this issue, and the options to correct it.

**Comment by paololucente** [comment]
Hi Rob ( @robcowart ),

Thanks very much for helping me catching-up. In essence: pmacct implementation was done at the ancient times of Cisco NBAR and much before that RFC from year 2012. Meanwhile, apparently, there is also a NBAR2 implementation that follows the RFC. Add to that that several collectors just look up in the Options the same value received in the Flows, this went undetected for some time. So, bottom line, good time to modernize.

The Options template now looks like this:

    FlowSet 5 [id=1] (Options Template): 4097
        FlowSet Id: Options Template(V9) (1)
        FlowSet Length: 22
        Options Template (Id = 4097) (Scope Count = 1; Data Count = 2)
            Template Id: 4097
            Option Scope Length: 4
            Option Length: 9
            Field (1/1) [Scope]: System
                Scope Type: System (1)
                Length: 4
            Field (1/2): APPLICATION_ID
                Type: APPLICATION_ID (95)
                Length: 5
            Field (2/2): APPLICATION_NAME
                Type: APPLICATION_NAME (96)
                Length: 32
                
And the Options Data look like this:

    FlowSet 6 [id=4097] (2 flows)
        FlowSet Id: (Data) (4097)
        FlowSet Length: 86
        [Template Frame: 1]
        Flow 1
            ScopeSystem: 00000000
            Classification Engine ID: Unknown (22)
            Selector ID: 00000001
            ApplicationName: FTP_CONTROL
        Flow 2
            ScopeSystem: 00000000
            Classification Engine ID: Unknown (22)
            Selector ID: 00000002
            ApplicationName: POP3

And Flow data is matching the same. SelectorID i left it to 4 bytes for now but it can be probably shortened to 2 bytes - which is the size of the field in nDPI. Does it look like we are back in business, true?

Paolo

**Comment by robcowart** [comment]
That looks good... and was QUICK! :-)

If you can send me a PCAP that includes the templates, option data and a few flows, I can test can replay and test it with our environment and tools.

**Comment by paololucente** [comment]
Nice stuff :-) Let me arrange one and send it to you by email. I failed to find yours online, can you please send me a quick email to https://github.com/pmacct/pmacct/blob/006132a0ad354f03bfb29e648b756721a4fbb965/AUTHORS#L6 ?

**Comment by robcowart** [comment]
If you look at the Netflow v9 template above. The option length should be 8, not 9. Because type and length values in a template are always 2 bytes each. The scope length and option length must always be even numbers.

If you correct this, the record decodes as expected. Here is an example of the app portion of a flow record that is enriched from the option data.

```json
"app": {
    "class": {
        "name": "ntop nDPI"
    },
    "id": "22..5",
    "name": "DNS"
},
```

**Comment by paololucente** [comment]
You are indeed right and i have just amended that & sent you an email with a new trace.

**Comment by robcowart** [comment]
Looks good! Thanks for the quick turnaround! Do you have an estimate when this will be rolled into a release?

**Comment by paololucente** [comment]
Fantastic. Next release should be around May-June period. But i can always issue a tag here on GitHub and/or make it a rc1 or something if there is at any point any urgency.

**Comment by FlorianHeigl** [comment]
@paololucente nice work! I just was debugging why I'm not getting any data, turns out the latest edgerouter X firmware had a pmacct version from 2013. Saved me many hours to see when you worked on this!
