### ISSUE TITLE
Empty input_snmp and output_snmp 

### ISSUE THREAD

**Issue by hedibertosilva** [pmacct/pmacct#479]
Hi, I'm noob in pmaact. I'm tring to export flows from Debian 10 and collect them with nfcapd in another server. 

So, the fields input_snmp and output_snmp are zero. Others fields looks like right.

`pmacctd.conf`

> daemonize: true
> aggregate: src_host,dst_host,src_port,dst_port,proto,tos,in_iface,out_iface,vlan
> plugins: nfprobe[192.168.0.2-9995]
> nfprobe_receiver[192.168.0.2-9995]: 192.168.0.2:9995
> nfprobe_version[192.168.0.2-9995]: 9
> nfprobe_timeouts[192.168.0.2-9995]: tcp=60:tcp.rst=60:tcp.fin=60:udp=60:icmp=60:general=60:maxlife=60:expint=15
> nfprobe_direction[192.168.0.2-9995]: in
> sampling_rate: 1

I tried to use _pre_tag_maps_ and _pcap_interfaces_map_ but nothing has changed.

I also tried to use sfprobe, but strange value is coming (like 1073741823). My ifindex is 2.

**Versions**

`pmacct -V`

> pmacct IMT plugin client, pmacct 1.7.6-git (RELEASE)
>  '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

`pmacctd -V`

> Promiscuous Mode Accounting Daemon, pmacctd 1.7.6-git [RELEASE]
> Arguments:
>  '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
> Libs:
> cdada 0.3.2
> libpcap version 1.8.1
> System:
> Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64
> Compiler:
> gcc 8.3.0
>

**Comment by paololucente** [comment]
Hi Hediberto ( @hedibertosilva  ),

libpcap - which is the underlying framework you are using to capture packets - is not integrated with the kernel and hence does not have concept of ifindexes. If you are looking for something integrated, you could check NFLOG and the uacctd daemon.

Otherwise, continuing on the libpcap path: did you check this document already? https://github.com/pmacct/pmacct/blob/1.7.6/QUICKSTART#L1417-#L1469 . If so, can you please post your integral config including the pre_tag_map (which is necessary) along with `nfprobe_direction` and `nfprobe_ifindex` config directives. 

> I also tried to use sfprobe, but strange value is coming (like 1073741823). My ifindex is 2.

1073741823 is 0x3FFFFFFF. in sFlow that is a "special" indicating that the input and/or output interface is not known (input and/or output depending which field the 0x3FFFFFFF is found). Which makes sense.

Paolo

**Comment by hedibertosilva** [comment]
Hi Paulo ( @paololucente ), 

Thank's for your support. I readed the document and tried to get better somethings but without success. This is my config now: 

**pretag.map**
```
set_tag=2       filter='src host 192.168.0.30'  label=eval_ifindexes
set_tag=2       filter='dst host 192.168.0.30'
set_tag=3       filter='src host 10.100.2.12'
set_tag=3       filter='dst host 10.100.2.12'
set_tag=7       filter='src host 10.200.0.1'
set_tag=7       filter='dst host 10.200.0.1'

set_tag2=1      filter='dst host 192.168.1.30'
set_tag2=2      filter='src host 192.168.1.30'
set_tag2=999    filter='net 0.0.0.0/0'
```
**pcap_interfaces.map**
```
ifindex=2       ifname=enp0s3
ifindex=3       ifname=enp0s8
ifindex=7       ifname=tun0
```
**pmacctd.conf**
```
daemonize: true
pre_tag_map: ./pretag.map
pcap_interfaces_map : ./pcap_interfaces.map
aggregate: src_host,dst_host,src_port,dst_port,proto,tos,in_iface,out_iface,vlan
plugins: nfprobe[192.168.0.2-9995]
nfprobe_receiver[192.168.0.2-9995]: 192.168.0.2:9995
nfprobe_version[192.168.0.2-9995]: 10
nfprobe_timeouts[192.168.0.2-9995]: tcp=60:tcp.rst=60:tcp.fin=60:udp=60:icmp=60:general=60:maxlife=60:expint=15
nfprobe_direction[192.168.0.2-9995]: tag2
nfproge_ifindex[192.168.0.2-9995]: tag
sampling_rate: 1
```
**collector output**
```
{                                    
        "type" : "FLOW",
        "sampled" : 0,
        "export_sysid" : 1,
        "t_first" : "2021-03-03T16:16:23.542",
        "t_last" : "2021-03-03T16:18:05.149",
        "proto" : 1,
        "src4_addr" : "1.1.1.1",
        "dst4_addr" : "192.168.0.30",
        "icmp_type" : 0,
        "icmp_code" : 0,
        "fwd_status" : 0,
        "tcp_flags" : "........",
        "src_tos" : 0,
        "in_packets" : 8,
        "in_bytes" : 672,
        "input_snmp" : 0,
        "output_snmp" : 0,
        "src_mask" : 0,
        "dst_mask" : 0,
        "dst_tos" : 0,
        "direction" : 0,
        "src_vlan" : 0,
        "dst_vlan" : 0,
        "ip4_router" : "XX.XX.XX.XX",
        "t_received" : "2021-03-03T16:18:05.928",
        "label" : "<none>"
}
```

**Comment by paololucente** [comment]
Hi @hedibertosilva ,

One update from my side. I did manage to reproduce the issue. There are two parts to it: 

1) direction not populated correctly, this is because your `pretag.map` needs a small fixing, see here:

```
set_tag=2       filter='src host 192.168.0.30'  jeq=eval_direction label=eval_ifindexes
set_tag=2       filter='dst host 192.168.0.30' jeq=eval_direction
[ .. ]
set_tag2=1      filter='dst host 192.168.1.30' label=eval_direction
set_tag2=2      filter='src host 192.168.1.30'
```

The above would do the following. For traffic sourced from 192.168.0.30, flow direction would be marked as `egress`, for traffic destined to 192.168.0.30, flow direction would be marked as `ingress`. You see the small tweaks to your original `pretag.map`, right? the `JEQs` (Jump On Equal) and the `label=eval_direction` set as target for the JEQs.

2) interfaces not populated correctly. This i could reproduce and smells like a bug. I will investigate further and keep you posted.

Paolo

**Comment by hedibertosilva** [comment]
Ohh, thanks a lot! The direction are populated correctly now. I'm looking forward to your reply about the interfaces.

**Comment by paololucente** [comment]
Hi @hedibertosilva ,

We have resolution! Wrt interfaces it was matter of a basic mispelling which i did not notice in your config, see how `nfprobe` was spelled `nfproge`: `nfproge_ifindex[192.168.0.2-9995]: tag`: fixing that g in b made also interfaces working for me. Haha, the easiest part took the longer time! :)

Paolo

**Comment by hedibertosilva** [comment]
Hi @paololucente ,

Sorry about that. You helped me a lot. Thank you!

**Comment by paololucente** [comment]
No worries & my pleasure.
