### ISSUE TITLE
Option to run bgpd as active BGP speaker  

### ISSUE THREAD

**Issue by Slepwin** [pmacct/pmacct#483]
Based on the documentation bgpd or nfacctd/sfacctd thread can only be run on passive mode and can't initiate BGP session.
Maybe daemons have an additional option to enable this or it may be added in future releases?

Example: We have deployment with 4 pods/containers in k8s cluster with Service (destination IP for IPFIX/Netflow), bbut I would also like to enrich netflow data from the bgp protocol - our Route Reflectors and/or border routers and need ability to establish BGP session from pods/containers directly to RR (dynamic-neighbor). With passive only we can't do it because PODs ephemeral by design and IPs can be changed at any time and we can't configure static neighbor on routers.

**Comment by paololucente** [comment]
Hi Alexander ( @Slepwin ),

Yes, the current implementation is only a BGP passive speaker one. Main reason back in the times was security. Also acting passively has lots of good implications: the BGP configuration on the pmacct side is minimal, almost zero, thanks to the fact you can read the BGP OPEN coming in and just mirroring it back stripping unsupported capabilities. Wanting pmacct to become an active speaker is kind of a major work (and not on the roadmap) because an infrastructure to define peers and session characteristics would have to be created.

I may suggest a different approach although i am not familiar with the setup you describe so i don't know the feasibility of what i am about to propose: you could have a host (or a couple for HA) outside this ephemeral environment to act only as NetFlow/IPIFX replicators and BGP x-connects (pmacct offers both features); this would give your infrastructure a fixed IP address as a target; then, with some scriptware that you should build by yourself, you can create / update / reload / etc. the mappings, ie. which flows and/or BGP sessions should be wired to which ephemeral element. 

Should the above sound like a viable idea, we may give it a try - contact me by unicast email as it will be plenty of back and forth.  

Paolo
