### ISSUE TITLE
PMACCT docker

### ISSUE THREAD

**Issue by Michael-MCP** [pmacct/pmacct#484]
I'm having a real issue getting started with the base docker image. On a Debian system docker run returns an error linked to the pmacctd config file. I couldn't find a clear guide to creating a config file so installed pmacct on the host to ensure I had a correct config file. I tried mount-binding the /etc/pmacct/ directory however this returns the same result.

```
# docker run -v pmacctd.conf:/etc/pmacct/pmacctd.conf pmacct/pmacctd
ERROR: [/etc/pmacct/pmacctd.conf] path is not a regular file.
```

have others had this issue?

**Comment by SanderDelden** [comment]
This is happening because Docker is mounting the file a a directory. In general it is best practice to not mount files as volume but instead use directories. In case you just want to mount the file you will have to specify the full path, for example:

`docker run -v /home/svd/src/nfa/pmacct/configs/pmacctd.conf:/etc/pmacct/pmacctd.conf pmacct/pmacctd`

Kind regards,
Sander

**Comment by msune** [comment]
@SanderDelden thanks for quickly jumping in.

@Michael-MCP as @SanderDelden there is a typo in the documentation `docker run -v` can be used for several things including named volumes (https://docs.docker.com/storage/volumes/).

To _just_ mount one file (bind mounts), the full path needs to be specified (see intro in https://docs.docker.com/storage/bind-mounts/):

>When you use a bind mount, a file or directory on the host machine is mounted into a container. The file or directory is referenced by its absolute path on the host machine. 

```
docker run -v [HOST_DIR/HOST_FILE]:[CONTAINER_DIR/CONTAINER_FILE] container name
```

That'd be:

```
marc@Mriya:~/tmp/test_docker$ touch pmacctd.conf
marc@Mriya:~/tmp/test_docker$ ls
pmacctd.conf
marc@Mriya:~/tmp/test_docker$ docker run -v /home/marc/tmp/test_docker/pmacctd.conf:/etc/pmacct/pmacctd.conf pmacct/pmacctd
WARN: [/etc/pmacct/pmacctd.conf] No plugin has been activated; defaulting to in-memory table.
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.6-git (20201226-0 (7ad9d1b))
INFO ( default/core ):  '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/etc/pmacct/pmacctd.conf'.
WARN ( default_memory/memory ): defaulting to SRC HOST aggregation.
WARN ( default/core ): Selecting a suitable devices.
INFO ( default/core ): [eth0,0] link type is: 1
OK ( default_memory/memory ): waiting for data on: '/tmp/collect.pipe'
^CINFO ( default/core ): OK, Exiting ...
NOTICE ( default/core ): +++
NOTICE ( default/core ): [eth0,0] received_packets=14 dropped_packets=0
NOTICE ( default/core ): ---
```

As noted by @SanderDelden one can also mount an entire directory, if all files in that directory are to be shared with the container, and again the explicit path to the directory is needed (`pwd`):

```
marc@Mriya:~/tmp/test_docker$ docker run -v `pwd`:/etc/pmacct/ pmacct/pmacctd
WARN: [/etc/pmacct/pmacctd.conf] No plugin has been activated; defaulting to in-memory table.
INFO ( default/core ): Promiscuous Mode Accounting Daemon, pmacctd 1.7.6-git (20201226-0 (7ad9d1b))
INFO ( default/core ):  '--enable-mysql' '--enable-pgsql' '--enable-sqlite3' '--enable-kafka' '--enable-geoipv2' '--enable-jansson' '--enable-rabbitmq' '--enable-nflog' '--enable-ndpi' '--enable-zmq' '--enable-avro' '--enable-serdes' '--enable-redis' '--enable-gnutls' 'AVRO_CFLAGS=-I/usr/local/avro/include' 'AVRO_LIBS=-L/usr/local/avro/lib -lavro' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
INFO ( default/core ): Reading configuration file '/etc/pmacct/pmacctd.conf'.
WARN ( default_memory/memory ): defaulting to SRC HOST aggregation.
WARN ( default/core ): Selecting a suitable devices.
INFO ( default/core ): [eth0,0] link type is: 1
OK ( default_memory/memory ): waiting for data on: '/tmp/collect.pipe'
^CINFO ( default/core ): OK, Exiting ...
NOTICE ( default/core ): +++
NOTICE ( default/core ): [eth0,0] received_packets=13 dropped_packets=0
NOTICE ( default/core ): ---

```

So @paololucente I think  `README.md` just needs to be fixed with the full path

---

Wrt to:

> In general it is best practice to not mount files as volumes but instead use directories.

@SanderDelden I was trying to find some references to that recommendation, but I couldn't. In fact, the very intro of https://docs.docker.com/storage/bind-mounts/, there is explicit mention on the option bind files. To the best of my knowledge both are used extensively, albeit I am by no means a docker expert.

It would be great if you can share some references, in case s/t different should be recommended in `README.md` of the project.
