### ISSUE TITLE
Kafka plugin output as CSV

### ISSUE THREAD

**Issue by hammieee** [pmacct/pmacct#508]
**Description**
1. Is there options to export netflow to kafka broker in CSV? How can I export the netflow in CSV format using kafka plugin?
2. How can I export netflow from pmaccts's nfprobe to nfacctd with kafka plugin in real time?

This is my current pmacctd.conf
> plugins: nfprobe
> nfprobe_receiver: 192.168.1.167:2111
> #daemonize: true
> nfprobe_version: 10
> nfprobe_timeouts: tcp=60:udp=60:icmp=60:general=60:maxlife=60
> timestamps_secs: true
> aggregate: src_host, dst_host,in_iface, out_iface, timestamp_start, timestamp_end, src_port, dst_port

This is my current nfacctd.conf
> kafka_topic: test
> kafka_broker_host: 127.0.0.1
> kafka_broker_port: 9092
> kafka_refresh_time: 30
> #kafka_history: 1m
> #kafka_history_roundoff: m
> #daemonize: true
> plugins: kafka
> nfacctd_time_new: true
> timestamps_since_epoch: true
> pcap_interface: ens33
> nfacctd_ip: 192.168.1.167
> nfacctd_port: 2111
> aggregate: src_host, dst_host,in_iface, out_iface, timestamp_start, timestamp_end, src_port, dst_port

**Version**

> NetFlow Accounting Daemon, nfacctd 1.7.6-git [RELEASE]
> 
> Arguments:
>  '--enable-kafka' '--enable-jansson' '--enable-ndpi' '--enable-debug' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'
> 
> Libs:
> cdada 0.3.2
> libpcap version 1.9.1 (with TPACKET_V3)
> rdkafka 1.2.1
> jansson 2.13.1
> nDPI 3.5.0-3116-c4084ca3
> 
> System:
> Linux 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64
> 
> Compiler:
> gcc 9.3.0

**Comment by paololucente** [comment]
Hi @hammieee ,

Thanks for getting in touch. 

Wrt shipping data in CSV format via Kafka. This is not supported and not on the roadmap; there is JSON for text-based format or Apache Avro for binary-based format (and also well integrated with Kafka and Confluent Platform). May i ask you the nature of your query though? CSV has never been implemented because it's not self-describing whereas Kafka does reason in terms of (batch of) messages: guess in a streaming data pipeline having non self-descriptive data like in CSV format where the title (needed to decode the tuples) is in some message back in the past. Curious to hear from you about this.

Also, can you please elaborate a bit more on your other question `How can I export netflow from pmaccts's nfprobe to nfacctd with kafka plugin in real time?`? Like, you don't like the fact that NetFlow/IPFIX does flow caching and hence there are certain timeouts before you get the data shipped to the collector? (in which case i may recommend to look at sFlow or set `nfprobe_dont_cache: true` if really wanting to stick to NetFlow/IPFIX. Otherwise you will have to enlighten me a bit on the nature of your query.

Paolo

**Comment by hammieee** [comment]
Hi @paololucente ,

Thank you for fast reply!

For the shipping of data in CSV format via Kafka, because we already had a kafka server that use CSV to parse them. We tried using Json but it is a lot slower comparing to CSV for high performance processing

On the second point, `nfprobe_dont_cache: true` works exactly as what I wanted!

**Comment by paololucente** [comment]
Hi @hammieee ,

True about slowness of JSON. Encoding / decoding there is little to do but you can at least counter the slowness coming from transmission by compressing with snappy (gzip will likely take more CPU resources for not doing a whole lot better job at it).

Also consider that JSON being self-descriptive (or Apache Avro to that matter) you can parallelize processing: you could define a topic with N partitions and consume messages with up to N consumers within the same consumer group load-sharing. With CSV you are effectively restricted to a single consumer process because of the title of the CSV - as soon as you try to parallelize it, only one consumer in the group will end up with the title and it would have to share it with the other consumers (kind of complex). 

Just my two cents. I am afraid i don't see a CSV encoding over Kafka coming up.

Paolo

**Comment by hammieee** [comment]
Thank you!
