### ISSUE TITLE
nDPI in nfacctd does not work

### ISSUE THREAD

**Issue by forever765** [pmacct/pmacct#525]
**Description**
I compiled pmacct with nDPI 3.4 and 4.0 respectively. When I use pmacctd to collect the server NIC traffic, I get the normal packet classification, such as "unknown/zabbix" or "unknown/ssh". But when I use nfacctd as the netflow collector, the CLASS column only shows "unknown". Can someone help me? Thanks in advance!

**Version**
softflowd version 1.0.0
nDPI version 3.4-stable
NetFlow Accounting Daemon, nfacctd 1.7.7-git [20210811-1 (e91a4bb)]

Arguments:
 '--prefix=/usr' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-debug' '--enable-geoipv2' '--enable-jansson' '--enable-ndpi' '--enable-kafka' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.3.5
libpcap version 1.5.3
rdkafka 0.11.5
jansson 2.13.1
MaxmindDB 1.2.0
nDPI 3.4.0

Plugins:
memory
print
nfprobe
sfprobe
tee
kafka

System:
Linux 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64

Compiler:
gcc 4.9.0

**softflowd config**
config softflowd
        option enabled        '1'
        option interface      'any'
        option pcap_file      ''
        option timeout        'maxlife=60'
        option max_flows      '8192'
        option host_port 'nfacctd.example.com:9995'
        option pid_file       '/var/run/softflowd.pid'
        option control_socket '/var/run/softflowd.ctl'
        option export_version '9'
        option hoplimit       ''
        option tracking_level 'full'
        option track_ipv6     '1'
        option sampling_rate  '1'

**Comment by forever765** [comment]
** nfacctd config **
plugins: print
print_refresh_time: 15
aggregate: class
nfacctd_port: 9995
snaplen: 750
classifier_num_roots: 51200
classifier_giveup_proto_tcp: 100000
classifier_giveup_proto_udp: 100000
classifier_giveup_proto_other: 100000
daemonize: false
debug: true
pidfile: /var/run/nfacctd.pid
logfile : /var/log/nfacctd.log

**Comment by paololucente** [comment]
Hi @forever765 ,

If i get correctly, you export data with softflowd and collect with nfacctd - and nfacctd prints all unknown. True? If so, the issue is extremely simple: softflowd does not support data classification and, once traffic is summarized in NetFlow data, it is not possible to do the DPI job anymore on it.

There is a solution though: you can use pmacctd and nfprobe plugin to export data with classification from nDPI and collect it back with nfacctd. See here: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L1306-#L1342 . You can use that basic config, tune to your needs and add `class` to the `aggregate` line.

Paolo

**Comment by forever765** [comment]
Hi @paololucente ,
Thank you for your reply. Your solution is helpful to me, I will try to use pmacctd, thanks!
