### ISSUE TITLE
pmacct logged packets that didn't match the filter rule

### ISSUE THREAD

**Issue by zzgundam** [pmacct/pmacct#584]
I want to log only the new tcp connection,the filter rule in config file like below:
pcap_filter: tcp[tcpflags] & (tcp-syn) != 0

but pmacct logged many packets that didn't match the filte rule,just like below:
select * from acct_20220301
where dst_port=56277 and ip_src='192.168.128.200' and ip_dst='192.168.129.2'
ip_src			ip_dst		src_port	dst_port	tcp_flags
192.168.128.200	192.168.129.2	80		56277	18
192.168.128.200	192.168.129.2	30000	56277	18

how to solve this problem?

**Comment by paololucente** [comment]
Hi @zzgundam ,

For future, you can experiment with filters - and what they would filter in / filter out - with tcpdump, it's the exact same syntax that pmacct accepts too. The expression that you did write `tcp[tcpflags] & (tcp-syn) != 0` does check if the SYN flag is activsated in order to filter in, that includes also SYN-ACK packets. Re-writing it to an exact match for SYN flag, ie. `tcp[tcpflags] == tcp-syn` does filter in only SYN packets.

Paolo
