### ISSUE TITLE
Need some clarification about aggregate_filter

### ISSUE THREAD

**Issue by AnanthGopal** [pmacct/pmacct#618]
**Description**
Hi @paololucente,

Thank you for this wonderful tool, We need some clarification about aggregate_filter

- We received two different ports like src_port and dst_port from pmacct, **src_port >= dst_port** how to add this validation in aggregate_filter.

- Similarly, we received ipv4 and ipv6 IP addresses(src IP and dst IP) in pmacct but we need only ipv4 IP data, how to add filter for this in aggregate_filter

is it possible to add this validation (**src_port >= dst_port**) in aggregate_filter?

**Comment by paololucente** [comment]
Hi @AnanthGopal ,

`aggregate_filter` syntax is based on libpcap. Any filter you can test it working in a tool like `tcpdump` and, if it works, it should work as a filter in pmacct too. I say this because you will see that there is tons of documentation around to help you express yourself with that syntax. This all said, i am not aware of anything of help for the first query, the `src_port >= dst_port`; for the second one, to allow v4 only the clause is `ip`.

Paolo
