### ISSUE TITLE
Further question about https://github.com/pmacct/pmacct/issues/609

### ISSUE THREAD

**Issue by DarmJarlo** [pmacct/pmacct#621]
https://github.com/pmacct/pmacct/issues/609
Thanks for the answer, but I still have this problem( it didn't always appear but still usually). Is the timeouts you have mentioned the timeout of the packets that I am monitoring or the packets that pmacctd sends to nfacctd? Actually, I have a problem with the exporting( pmacctd sent flow very later)
And another question is that when I am using sampling rate ， sometimes I receive fewer packets as expected（for example，I send 350000 packets from host1 to host2 and sampling rate is 5000， sometimes I received rightly 70 packets but sometimes I only got 7 packets，I am using the ciciddos2019 dataset）.Do you know why?
Thanks,
Jar

**Comment by paololucente** [comment]
> Is the timeouts you have mentioned the timeout of the packets that I am monitoring or the packets that pmacctd sends to nfacctd?

The standard NetFlow / IPFIX metering process does encompass a cache of flows to be exported. Those timeouts that i did mention do influence such purging process. 

> And another question is that when I am using sampling rate ， sometimes I receive fewer packets as expected（for example，I send 350000 packets from host1 to host2 and sampling rate is 5000， sometimes I received rightly 70 packets but sometimes I only got 7 packets，I am using the ciciddos2019 dataset）.Do you know why?

Can you qualify this better? Do you receive 70 or 7 NetFlow / IPFIX packets? If so, what about their content, since one NetFlow / IPFIX packet can include one or several traffic flows.

> I would like to configure an adaptive sampling-rate( query the database and get the number of received packets then according to this number of packets ,automatically modify the sampling_rate of the pmacctd config.I try to make this change because I found sometimes when there are too many captured traffic which makes the database queries very slow.

One approach could be to use the fss / fsrc pre-processors in conjunction with your relational database, see: https://github.com/pmacct/pmacct/blob/master/CONFIG-KEYS#L1541-L1565 . Problem being if they do not work out of the box for you, you are a bit on your own.

Another approach is that using a relational database (be it MySQL or MariaDB) with that 5-tuple + timestamps (de-)aggregation, you will find sooner or later that it's not going to scale - any relational database won't. So you could take the opportunity to swap the database: Apache Druid, ClickHouse, TimescaleDB are the first three that come to mind. If you know how to operate a PostgreSQL, probably TimescaleDB is a good choice to start.

Finally, sure, as it stands the adaptive sampling avenue is a no-go as by restarting pmacct to re-configure it with a new sampling rate, you are going to loose heaps of in-flight traffic. The right way to do this would be an algorithm inside pmacct or a mechanism to signal a new sampling rate to pmacct -- the latter being the simplest / quickest of the two. But both do require coding. 

Paolo

**Comment by DarmJarlo** [comment]
Hello Paolo, thanks very much for your answer!
As you have reminded me of another issue, I got actually always flows containing only one packet. Can I combine multiple packets into one flow?
And as for the adaptive sampling rate, you have rights. And I have considered this adaptive sampling rate is unnecessary because the bandwidth in realworld is limited.....
The last question maybe, I have found on my side the nfacctd process is always a core process and I cannot kill it unless I reboot. So this brings me a problem, when I restart a nfacctd. It shows me always that I still have the former nfacctd process.I dont know ,but maybe this parallel process makes nfacctd not always work well. So do you have any advice to deal with it?

Jia

**Comment by paololucente** [comment]
> As you have reminded me of another issue, I got actually always flows containing only one packet. Can I combine multiple packets into one flow?

The more time you cache a flow, the more packets belonging to it may be sampled. So any trying to optimize telemetry (NetFlow / IPFIX) on the wire is effectively inversely functional to performance / short timeout.

> The last question maybe, I have found on my side the nfacctd process is always a core process and I cannot kill it unless I reboot. So this brings me a problem, when I restart a nfacctd. It shows me always that I still have the former nfacctd process.I dont know ,but maybe this parallel process makes nfacctd not always work well. So do you have any advice to deal with it?

Not sure, why that would be the case. At least nothing can defeat a brutal `killall -9 nfacctd`. 

Paolo
