### ISSUE TITLE
Question about imt_buckets

### ISSUE THREAD

**Issue by ElizavetaFirst** [pmacct/pmacct#627]
**Description**
Hello! I faced with problem of missing packets. When I play big tcp dump some packets are lost in memory plugin. Type of traffic - netflow nsel. I noticed that packets are added to the queue by the number equal to the config.buckets and this parametr is equal to config parametr imt_buckets. When I multiply this parameter by 10, the events are no longer lost. Could you please describe why you use parameter instead of packets count and how I can prevent loosing of packets.

**Version**
nfacctd 1.7.5-git

**Comment by paololucente** [comment]
Hi @ElizavetaFirst , 

Increasing the number of buckets will probably make the conflict chains of the hash shorter - and hence the memory structure more performing. Probably when you leave on default settings where you experience the data loss, maybe if you check the plugin you will find it pegging 100% on the CPU. Did you check pmacct logs? Did it warn you that data loss was ongoing?

If i get your question right wrt `why you use parameter instead of packets count`, i may say that packet count is not known upfront even when replaying a trace and, best of all, that would not work when working against live traffic. 

Paolo
