### ISSUE TITLE
avro kafka schema name

### ISSUE THREAD

**Issue by mooneym17** [pmacct/pmacct#636]
**Description**
using your docker image, with kafka plugin, avro format and schema registery - the schema name does not match topic. We see <topic>-acct_data appened. 

config:
plugins: kafka[ic]
!
! 'ic' plugin configuration
!
aggregate[ic]: src_host, dst_host, src_net, dst_net, peer_src_ip, peer_dst_ip, in_iface, out_iface, timestamp_start, timestamp_end, src_port, dst_port, proto, tos, src_mask, dst_mask, src_as, dst_as, tcpflags, sampling_rate, sampling_direction
kafka_topic[ic]: ipfix-ic
kafka_broker_host[ic]: 127.0.0.1
kafka_broker_port[ic]: 9092
kafka_partition_dynamic[ic]: true
kafka_partition_key[ic]: $peer_src_ip
kafka_output[ic]: avro
kafka_refresh_time[ic]: 10
kafka_avro_schema_registry[ic]: http://127.0.0.1:8081
!avro_schema_file[ic]: /opt/ipfip_out//avro_schema_file
timestamps_since_epoch[ic]: true

**Version**
Provide the version in use. An output of -V is typically good, ie. `nfacctd -V`
NetFlow Accounting Daemon, nfacctd 1.7.8-git [20220901-0 (8319cd1d)] 

**Appreciation**
Please consider starring this project to boost our reach on github!

**Comment by paololucente** [comment]
Hi @mooneym17 ,

Thanks for bringing this up. This is done in order to distinguish the proper data schema from start / close messages, which have a different schema. See here: https://github.com/pmacct/pmacct/blob/master/src/kafka_plugin.c#L106-L108 . Let me qualify better what is your proposal: do you propose to at least document this (very fair & my bad!) or is this hampering your setup?

Paolo

**Comment by mooneym17** [comment]
Hi Paolo,

Thanks for getting back to me. I was looking at using this data with ksql but it seems to expect the schema to follow the  a specific format eg:<topicname>-value .

https://docs.ksqldb.io/en/latest/operate-and-deploy/schema-registry-integration/
"The key and value schemas must be registered in Schema Registry under the subjects pageviews-avro-topic-key and pageviews-avro-topic-value, respectively."

**Comment by marcotollini** [comment]
Hello @mooneym17 ,

Let me help you out here, and maybe remove a bit of confusion in the topic.
As you probably know, Kafka is unaware of any encoding, or message type, or, in other words, it does not understand that you are using a schema registry or not. At the end, a kafka message is just a series of Bytes, and this is what Kafka knows.

To use the schema registry, you are using special version of Kafka Producer and Consumer maintained by Kafka. You producer will take a JSON message and a schema, it will go to the schema registry to register the schema and the registry will return the ID back. Then, the producer will proceed to encode the JSON message in AVRO by using the schema it has just registered, and finally it pre-appends 0, and the ID of the schema (received upon registration from the schema registry) to the encoded message. Checkout here the format of an AVRO encoded message with schema registry support: https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#wire-format
As you can see, you do not need the Subject name to decode the message, as the consumer can get the schema ID from the message itself, go to the registry, query via the ID, and get the schema back. Finally, it can use the schema to decode the AVRO message.

All good and shiny, but the schema registry is mostly there to guarantee backward and forward compatibility (pmacct does NOT guarantee backward and forward compatibility!), and in this way we are not really taking advantage of this feature.

Introducing subjects in schema registry. When you register a schema, you want to give it a subject, so that the schema registry can check the compatibility with the previous versions of a subject. Basically the producer sends to the schema registry (schema, subject name), the schema registry goes to the subject name and check that the schema just sent is compatible with the previously registered versions of that subject. If the compatibility checks are ok, then the schema registry creates a new version in that subject and link the ID of the schema to the version.

How do you choose the schema name? Confluent defines clear instructions via the "subject name strategy": https://docs.confluent.io/platform/current/schema-registry/serdes-develop/index.html#subject-name-strategy

In the default strategy (TopicNameStrategy) your subject name is {topic name}-value for the value field in the kafka message, and {topic name}-key for the key value in the kafka message. This is what kSQL expects and this is why you see that it expects pageviews-avro-topic-value: your topic name is pageviews-avro-topic.

Why pmacct cannot use TopicNameStrategy, and it is using TopicRecordNameStrategy instead? As Paolo was mentioning, in your topic you will find 3 different types of messages: acct_init, acct_data, and acct_close. Where init and close are used to determine the start and the finish of a dump, and acct_data is used to transmit the actual data.
As you can quickly see, the TopicNameStrategy supports only one schema per topic value (defined in {topic name}-value), while TopicNameStrategy supports multiple schemas in one topic. In our case, if you go to your schema registry you will see ({topic name}-acct_init, {topic name}-acct_data, {topic name}-acct_close).

Making pmacct compatible with TopicNameStrategy would be nice, but extremely hard.

What can you do? Well, I have almost 0 experience with kSQL, but it seems that Confluent did not yet added the support for the different subject naming strategies, unfortunately. My suggestion for you is to provide the schema ID directly (https://docs.ksqldb.io/en/latest/operate-and-deploy/schema-inference-with-id/) and somehow discard all the messages that are not being decoded by that schema ID (the minority anyway if you have traffic). An alternative is to use JSON, or to create a processing jobs which reads from the pmacct topic, filters out the init and close, and pushes only the acct_data messages in another topic, which then is read by kSQL.

**Comment by mooneym17** [comment]
@marcotollini thank you. I was just exploring and avro looked like a nice option  for me a as the schema would be generated. As you say, JSON is also an option and works well for my tests.

Thanks for the great explanation! 

Great project by the way!
