### ISSUE TITLE
several tee plugins: reporting agents to sql

### ISSUE THREAD

**Issue by tomadeb** [pmacct/pmacct#642]
This is more of help or feature request.

I maintain several servers, each running multiple instances of nfacctd with the tee plugin.

I'd like to add the sql plugin to instance so that they can report on agent_ids received by eaxch of these instances. Based on my investigations of the various sql versions, there doesn't seem to be any good sql structure to satisfy this use case. 

I'd mostly interested in the following primitives/fields:
- agent_id
- sampling_rate 
- host (machine running the nfacctd instance)
- port (port configured in this nfacctd instance)
- timestamp of first netflow packet received from this agent 
- timestamp of last netflow packet received from this agent

Is this possible? could you point me in the right direction to achieve this 

thanks in advance

**Comment by paololucente** [comment]
Hi @tomadeb ,

Thanks for reaching out. Since you speak `nfacctd`, i guess what by `agent_id` you do refer to is the IP address of the NetFlow / IPFIX exporter, isn't it? In pmacct jargon that is mapped to the `peer_src_ip` primitive (i say this to not confuse with agent_id of sFlow or agent_id coming out of a `pre_tag_map`).

Also, no, you can't have the collector IP / port in the DB but you can easily issue tags for that - would it help? The simplest i can come up with is `post_tag: <collector id>` where <collector id> is something that is going to be meaningful to you as part of the post-processing.

The above clarified, are you asking how to generally send over a custom tuple from pmacct to a SQL database? If so: 
* Intro to the topic: https://github.com/pmacct/pmacct/blob/master/QUICKSTART#L335-L397
* Where to find all primitives kung-fu: https://github.com/pmacct/pmacct/blob/master/sql/README.mysql
  - You did not specify which DB you are using but, i am sure, you can find your way with the other READMEs in that dir

The aggregate that you are looking for would be:

`aggregate: tag, peer_src_ip, timestamp_start, timestamp_end, sampling_rate`

Also in your config you want:

sql_optimize_clauses: true
sql_table: <table name>
sql_table_version: 9

Tag, as we said, is issued by adding a `post_tag: <collector id>` line to your config.

A basic CREATE TABLE statement is (please read all knobs you have to make timestamps less granular, optimize storage space for IP addresses, make tables creation dynamic with sql_table_schema, etc.):

DROP TABLE IF EXISTS acct;
CREATE TABLE <table name> (
	tag INT(4) UNSIGNED NOT NULL,
	peer_ip_src CHAR(45) NOT NULL,
	timestamp_start DATETIME NOT NULL,
	timestamp_start_residual INT NOT NULL,
	timestamp_end DATETIME NOT NULL,
	timestamp_end_residual INT NOT NULL,
	sampling_rate INT(4) UNSIGNED NOT NULL,
	packets INT UNSIGNED NOT NULL,
	bytes BIGINT UNSIGNED NOT NULL,
	stamp_inserted DATETIME NOT NULL,
	stamp_updated DATETIME,
	PRIMARY KEY (tag, peer_ip_src, timestamp_start, timestamp_end, sampling_rate, stamp_inserted)
); 

Paolo

**Comment by tomadeb** [comment]
Hi @paololucente,

thank you very much for your quick response. I'll be testing your suggestions shortly.
