### ISSUE TITLE
Sub-minute time-bins?

### ISSUE THREAD

**Issue by floatingstatic** [pmacct/pmacct#661]
**Description**

I am trying to keep 5 second (or any sub 1min value) time bins and and align flushing the cache of those bins (refresh_time) when we roll over to a new bin. I do this as we have a very broad aggregation that ends up being many records so I want to somewhat aggregate but flush at very short intervals. I tried something like this:

```
kafka_refresh_time[raw]: 5
kafka_history[raw]: 5s
```

However I end up getting:

```
WARN: [/etc/pmacct/sfacctd.conf] Ignoring invalid time value: 5 (residual secs afters conversion in mins)
```

This appears to happen here in the code here: https://github.com/pmacct/pmacct/blob/cfb820f18d5c0fe221d5401b9900397854a2ec9e/src/cfg_handlers.c#L6628-L6631

When I look at the [CONFIG.KEYS](https://github.com/pmacct/pmacct/blob/cfb820f18d5c0fe221d5401b9900397854a2ec9e/CONFIG-KEYS#L1344) documentation it seems that units of seconds are supported however my read of the code makes me think this is only possible if the seconds are modulo 60 second intervals (minute) which does not appear to be documented.

Is this a lapse in the documentation or is it expected that time bins are fixed to minutes and we cannot go lower than this?

For what its worth this seems to work mostly ok for my needs but it might be nice to have sub-minute bins:

```
kafka_refresh_time[raw]: 5
kafka_history[raw]: 1m
```

`stamp_inserted` ends up being the minute for the time bin and flushes that occur via refresh time show `stamp_updated` with different values (and thankfully it appears that byte/packet counters are reset with every flush/refresh!). So that kinda gets me what I need but nice rounded bin values via `stamp_inserted` in our records flushed to kafka would be nice.

**Version**
1.7.8 (docker)

**Appreciation**
❤️ pmacct!

**Comment by paololucente** [comment]
Hi Jeremiah ( @floatingstatic  ),

Thanks for raising this. You are right, times expressed in seconds for `kafka_history` must be minute-aligned, hence effectively making the minimum resolution for history 1 minute (as the most immediate step, i will review documentation to reflect reality). The background on why then times in seconds were introduced is because people liked to express all in seconds, both refresh_time and history. 

Making history supporting sub-second (then i would introduce a check to make sure less than 60 seconds were specified, just to not let it be unbound) is indeed possible, there is no technical limit preventing it from happening, we should only make sure that the algorithms that do increment time and stuff they do hold up; if you have a spare minute, since you have the scenario fresh in your mind, can you try to just remove the check there in `cfg_handlers.c` and see if overall all works well if you specify `kafka_history[raw]: 5s`?

Paolo

**Comment by floatingstatic** [comment]
Hi @paololucente thanks for confirming. Yes I'm happy to give this a try and will report back!

**Comment by floatingstatic** [comment]
@paololucente this appeared to work very well in my testing. I opened #662 ... feel free to edit or revise as needed.

**Comment by paololucente** [comment]
Hi Jeremiah,

I just passed the patch i was referring to in #662. It seems to work for me, can you confirm working OK for you too?

Paolo

**Comment by floatingstatic** [comment]
Hi @paololucente, I tested compiling from the latest master and was able to re-run my tests. Everything still looks good. I will ahead and close this issue. Thank you again for your excellent/quick support on this. As always I appreciate what you do!
