### ISSUE TITLE
Configuration Question

### ISSUE THREAD

**Issue by buckwheattb** [pmacct/pmacct#692]
Hello,

We are using PMACCT to gather NetFlow data from various devices on our network.  I am having some difficulty in getting aggregate information on a "Per Flow" basis.

What I mean by that is I am looking to gather aggregated data between various endpoints on the network, but I am looking for a more granular breakdown of those communications (per flow record).

For example:

- 8am, ServerA initiates a connection to ServerX on port 80.  The next series of flows (between ServerA and ServerX) represent a total data transfer of 1MB.
- 11am, ServerA again initiates a connection to ServerX on port 80.  The series of flows that make up that conversation represent a total transfer of 2MB

I am looking to capture 2 distinct records (one for the 8am conversation and another for the 11am conversation) and store that data into a PostgreSQL database.

Is there a mechanism where I can tell PMACCT to perform aggregation based on a flow conversation and not just between the Src->Dst?

Thank you in advance for your help

**Comment by buckwheattb** [comment]
hello,
thank you for the reply.

What I'm trying to get down to would be individual flow ID's, or a combination of primitives that would uniquely identify each conversation between hosts aggregating the sum of the bytes between the SYN and FIN or RST flags.

Example:
If I open a connection to a web server, a flow is initiated via a SYN flag...

something like this:  srcip:  192.168.0.50, srcport:  52101, dstip:  4.2.2.2, dstport:  80, proto:  TCP bytes:  64, SYN (i'm leaving out a lot of other fields I know, but this is predominantly what i'm looking to track).
a series of subsequent flows occur during this "conversation" finalizing on either a FIN or RST flag (if I am understanding NetFlow correctly).  If I then click a link on that web page, a new set of flows are initiated for that conversation, again beginning with the SYN and ending with FIN or RST.  

Ultimately, this could represent hundreds of flows or conversations during my overall interaction with that web host

I would like to track each "conversation" individually along with the sum of the bytes so that not only can I see the total amount of data transmitted between hosts, but also how many times a source has initiated a conversation to another host so I can output something similar to below (again, totally made up):

Srcip                 Dstip      Proto    Port    Total Conversations       Total Bytes
192.168.0.50     4.2.2.2     TCP       80      200                                4200158
192.168.0.50     4.2.2.2     UDP      123    5000                              154785

If I can get each conversation logged, I can also plot that along a timeline to see not only bandwidth consumption, but also connections over time.

Is there a "Flow ID" or something similar that can uniquely identify each conversation between hosts?

I hope I described that effectively.

Thank you again

**Comment by paololucente** [comment]
Hi @buckwheattb ,

I see, it is more clear now with the example. And let me say that what you want to achieve is not directly supported by pmacct - moreover the fact you don't want flows but conversations is tricky, consider for example that a long-lived conversation can be chopped in several flows (because of cache occupancy or any other configured timeouts).

Should you want to over-simplify things, ie. consider a relationship 1:1 between flows exported and conversations, you can simply add the `flows` primitive to your `aggregate`. 

But depending on the traffic type and other conditions, as i was saying, you may find this inaccurate. You could then try to use `nfacctd_stitching: true`, read more about it here: https://github.com/pmacct/pmacct/blob/ef668563f7fd5d8a46b623fa96d76e40116c0191/CONFIG-KEYS#L1969 to identify the conversations. But then this will take a greater toll on your storage and you will have to make sums yourself as part of post-processing.

Paolo



Paolo

**Comment by buckwheattb** [comment]
I see...I'll check that option out.

Thank you for your help!
