### ISSUE TITLE
Setup pmacct without BGP on a simple A-B Linux router?

### ISSUE THREAD

**Issue by RoFz** [pmacct/pmacct#721]
**Description**
This is a question/information request. Is it possible to use pmacct on a simple Linux router without BGP? This Linux device is already the default gateway of particular network segment/subnet, so the traffic is already being forwarded from one interface to the other. Since there's no BGP involved, I was thinking about just adding subnet labels in the networks_file.
Is this achievable? If yes, is there any documentation on this setup? 

I've been following this fine [guide](https://brooks.sh/2019/11/17/network-flow-analysis-with-prometheus/), but I'm kind of lost now trying to fit the remaining blocks of the puzzle without the BGP part.

**Version**
```
NetFlow Accounting Daemon, nfacctd 1.7.8-git [RELEASE]

Arguments:
 '--enable-kafka' '--enable-jansson' '--enable-l2' '--enable-traffic-bins' '--enable-bgp-bins' '--enable-bmp-bins' '--enable-st-bins'

Libs:
cdada 0.4.0
libpcap version 1.10.1 (with TPACKET_V3)
rdkafka 1.8.0
jansson 2.13.1

Plugins:
memory
print
nfprobe
sfprobe
tee
kafka

System:
Linux 5.15.0-82-generic #91-Ubuntu SMP Mon Aug 14 14:19:18 UTC 2023 aarch64

Compiler:
gcc 11.4.0

For suggestions, critics, bugs, contact me: Paolo Lucente <paolo@pmacct.net>.
```

**Appreciation**
Done

**Comment by paololucente** [comment]
Hi @RoFz ,

What you are trying to achieve is indeed possible: no BGP so, as you said, you define a `networks_file` where you list subnets of interest one per line, link such file in the config, ie. `networks_file: /path/to/networks.lst`, and set `aggregate: src_net, dst_net` for a test -- this config should show the traffic in between the subnets you did define in the file.

As per labelling, unfortunately that feature got dropped -- i refer to the one where you could define strings like foo or bar in the networks_file and would see those accounted traffic for, instead of the actual defined subnet. The feature was clumsy and it is definitely something better done as part of a lookup when post-processing data.

Should you want some form of grouping of subnets, you could still group them using ASNs (say private ones). You could refer to the following section of the example:

```
65500,192.168.1.0/24
65501,192.168.2.0/25
65502,192.168.4.0/23
```

Now if you, again for a test, configure `aggregate: src_net, dst_net, src_as, dst_as` then you should see both the subnets and the ASNs (which in this case are just numerical groups of subnets). Should you then want the ASN be translated into strings like foo, bar, etc. then you need to do it in the post-processing but now it's much easier as groups are made ready and it would be a trivial task of 1:1 translation.

Paolo
