### ISSUE TITLE
Create pipeline to add information to PMACCT flows

### ISSUE THREAD

**Issue by balioune** [pmacct/pmacct#746]
Hi all,
I would like to create a pipeline line in goflow2. The idea is to enriche the decoded flow by PMACCT before sending it to Kafka.

I want to add usefull infomation like application e.g: google, https, etc.

I already have a python application that can enriche flow, how can I integrate twith PMACCT ?

Best Regards

**Comment by paololucente** [comment]
Hi @balioune ,

I assume the data input is NetFlow IPFIX, right? Is the application information already part of the flow data? Or are flows including a portion of the data packet, a-la IE 315, so that nDPI can be run against it? Otherwise i am afraid i would need some more information in order to help.

In general, say you want to post-process decoded data, you could run a trigger, ie. `print_trigger_exec`. The idea could be to let pmacct output to a file, run the trigger script against it to perform post-process / enrichment, then ship the modified / final output to Kafka.

Paolo
