### ISSUE TITLE
nfacctd: print plugin -- writer [netflow] multiple processes are created and consume 40% of my system memory

### ISSUE THREAD

**Issue by hemant61201** [pmacct/pmacct#787]
I implemented nfacctd version 1.7.1 and encountered an issue with the nfacctd print plugin. Multiple processes were created by the writer [netflow], consuming 40% of my system memory, and I observed a flow rate of around 15-17k EPS.

**Comment by paololucente** [comment]
Hi @hemant61201 ,

Can you share your configuration? This may depend on the selected (de-)aggregation along with caching time (refresh time). Also can you confirm which version are you using? 1.7.1 or 1.7.10. If 1.7.1, as you mentioned, that is not supported anymore and i'd advice to upgrade to something more recent.

Paolo

**Comment by hemant61201** [comment]
Hi @paololucente,

I upgraded pmacct version to 1.7.9 but still i faced the same issue.

Here i Attached the screen shots :
![nfacctd_processes](https://github.com/pmacct/pmacct/assets/79056728/b5cf4123-8a61-41b1-af92-95adf04c76dd)
![nfacctd_version](https://github.com/pmacct/pmacct/assets/79056728/0123fb98-7422-4461-8f97-4c2e74f9e20d)

**Comment by paololucente** [comment]
Hi @hemant61201 ,

The `urgent` writers are triggered by the fact the cache space of the plugin is finished. This is related to the (de-)aggregation method you configured: the more flows you have, the more you de-aggregate, the more cache space you need in order to keep in memory all the entries for the wanted refresh time (by default 60 seconds). Also, because you write to a fixed file `NetFlow` (argument to `print_output_file[NetFlow]`), the writers will tend to lock out with each other.

My recommendations:

1) add at least a %s to the file name, ie.: `print_output_file[NetFlow]: NetFlow_%s`;
2) increase the cache space (of course this is limited by the memory available, `print_cache_entries`, read more here: https://github.com/pmacct/pmacct/blob/c7a3d06c4b7f12d37e54297a8e333f1615c399ab/CONFIG-KEYS#L1422 ) or reduce the time interval to write to files (`print_refresh_time`, read more here: https://github.com/pmacct/pmacct/blob/c7a3d06c4b7f12d37e54297a8e333f1615c399ab/CONFIG-KEYS#L1338 )
