### ISSUE TITLE
Release of 1.7.9?

### ISSUE THREAD

**Issue by JonMurphy** [pmacct/pmacct#791]
>Yes, this will be part of 1.7.9. There is no committed date yet for its release but for sure it will be by the end of the year, with code freeze & version bump already taking place in a couple of months. This said, please start having a test to current code so to see all is working good for you. Keep me posted. Paolo

_Originally posted by @paololucente in https://github.com/pmacct/pmacct/issues/696#issuecomment-1622634748_
            
Hi @paololucent, Hope all is well!
Sorry for begging, but I am hoping for a new release.  Could release 1.7.9 be built up and released?
Best regards,
Jon

**Comment by paololucente** [comment]
Hi Jon ( @JonMurphy ),

Timely message as right yesterday there was more cherry-picking from master. Essentially 1.7.9 to be released we are waiting (and working hard) to wrap up #768 and #777 , which turned out to be closely related. I hope 1.7.9 can be released soon. In addition to that with the unvaluable help of Marc ( @msune ) we are trying also to make a Docker image for candidate release code -- which would hopefully improve quality (testing) and easier access to code on freeze / about to be released.

Paolo

**Comment by paololucente** [comment]
Hi Jon ( @JonMurphy ),

The 1.7.9-rc3 tag was now made for latest code in 1.7.9 branch. Along with it, docker containers are created for it. If eager to give a try to 1.7.9 code base (and help testing out), please download it. Hopefully this code will be the final one for the 1.7.9 release.

Paolo

**Comment by paololucente** [comment]
Hi Jon ( @JonMurphy ),

Closing this one up as 1.7.9 was released: https://github.com/pmacct/pmacct/releases/tag/v1.7.9

Paolo
