### ISSUE TITLE
v2 sflow counters not being processed

### ISSUE THREAD

**Issue by johanek** [pmacct/pmacct#94]
Hello,

I am collecting sflow counters with sfacctd successfully, but some of my devices are sending sflow v2 datagrams and these are not being processed.

I've tried the simplest possible config:
```
sfacctd_port: 23503
daemonize: false
sfacctd_counter_file: /tmp/counters
```

Running in debug mode, I see the packets being received:

```DEBUG ( default/core ): Received sFlow packet from [<ipaddress>:4815] version [2] seqno [315334925]```

I can also successfully receive the data with sflowtool. But I only get the following records being output to /tmp/counters:

```{"seq": 0, "timestamp": "2017-01-26 09:18:33.108082", "peer_src_ip": "<ipaddress>", "event_type": "log_init"}```

When I configure sfacctd to export the flows for these devices, this is working fine, it's only counters which aren't being processed.

I'm at a loss of what to do next to debug this, I would appreciate any advice.

Thanks!

**Comment by paololucente** [comment]
Hi Johan,

It makes sense to patch the documentation in this sense - sFlow v2/v4 counters are currently not supported: this is for two reasons: 1) i didn't have v2/v4 data available to test against and 2) since the sFlow counters development took place in late 2015 i thought .. does anybody still run v2/v4 by now? :)

It should not be much work to support v2/v4. I propose as next step: can you send me via unicast email a trace of some of these packets so that i can replay them in lab?

Thanks,
Paolo

**Comment by johanek** [comment]
Hi Paolo,

Thanks very much - I'll send this through in a few days day.

**Comment by paololucente** [comment]
Hi Johan,

This should be addressed by the last commit. Can you give it a try and verify it working for you? I did test it working in lab against the trace you graciously provided.

Cheers,
Paolo

**Comment by johanek** [comment]
Hiya,

I've tested the current master, and the sflow v2 counters are being processed as expected.

Thanks!
